### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pedro2555** [vatsimnetwork/vatspy-data-project#10]
Can you include a license file with the project?

**Comment by FlynZSky** [comment]
Data was originally distributed by ServInfo and used with permission. Neither the developer or this project claim ownership of the data and will not dictate licensing for the data. The data is additionally freely available via other sources on the web.

**Comment by pedro2555** [comment]
Fair enough. Is it OK to distribute this files with a packaged application then?

**Comment by pedro2555** [comment]
@FlynZSky Is there a reason to delete my comment? I'm trying to use this in a personal project.

I just don't want to use without permission and then get in trouble with you guys.

I also have a bunch of changes to submit adding several airports and aerodromes, is just waiting for a final decision in whether I can or cannot use this project.
