### ISSUE TITLE
ZUGY_CTR missing

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#102]
![image](https://user-images.githubusercontent.com/35482228/93715063-28a00380-fb67-11ea-84e0-a1877a832de5.png)

Controller info: Callsign Guiyang Control CN/EN ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ CPDLC/PDC LOGON GYCT^Â§Cover ZUGY ACC 7800m-GND, ZUGY/AS/PS/BJ/ZY/KJ^Â§China METRIC RVSM in use -> vats.im/rvsm

**Comment by amosngSP** [comment]
Refer to pull request #161
