### ISSUE TITLE
ESOS, Sweden: invalid geometry due to self intersect. 

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#110]
Self intersect in the northern tip of Sweden/border with Norway
![image](https://user-images.githubusercontent.com/42404718/95966738-c657bd00-0e0b-11eb-8858-39001a5eda28.png)
![image](https://user-images.githubusercontent.com/42404718/95966746-c9eb4400-0e0b-11eb-9261-a37ce5cdf495.png)

**Comment by Adrian2k** [comment]
Fixing
