### ISSUE TITLE
EDGG-N

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#113]
1) strange extrusion in EDGG-N sector (highlighted in yellow)
2) Sector label location, and actual geometry location mixed up in multiple EDGG sectors. 
(in below picture, label is shown in center of geometry with that name)

![image](https://user-images.githubusercontent.com/42404718/95967722-db811b80-0e0c-11eb-85be-76cc132ad754.png)

**Comment by Adrian2k** [comment]
Fixing

**Comment by NelisV** [comment]
Might wanna hold off on this, the german guys are sending over a KMT with the right sector split. will upload when i get it.

**Comment by Lotus3xiG3** [comment]
Did you just fix the issue with the outdated EDGG_NW sectors or update all the sectors?

**Comment by Adrian2k** [comment]
> @Adrian2k Did you just fix the issue with the outdated EDGG_NW sectors or update all the sectors?

I fixed the geometry issue with EDGG_N sector only (and moved it to be north of sector west). 
Was there an issue with EDGG_NW as well?

However as I told @NelisV via discord PM: The German sectors can still be amended after my pull request is merged.

**Comment by Lotus3xiG3** [comment]
Okay, thanks for that. But actually the sectors itself are completely outdated and these will be updated by us. Those new sectors make no use of the old borders, so we gotta redo these anyways. But I will open a new issue for that.

**Comment by prryplatypus** [comment]
Sector updates discussion continues in #122 😛
