### ISSUE TITLE
LWSS, North Macedonia: invalid geometry due to self intersect. 

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#114]
see red dot
![image](https://user-images.githubusercontent.com/42404718/95967950-2bf87900-0e0d-11eb-93fc-119ef66c367a.png)
![image](https://user-images.githubusercontent.com/42404718/95967981-387cd180-0e0d-11eb-8d9a-f8c2392da0d8.png)

**Comment by Adrian2k** [comment]
Fixing
