### ISSUE TITLE
TJZS, San Juan, double vector western edge 

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#115]
![image](https://user-images.githubusercontent.com/42404718/95968164-69f59d00-0e0d-11eb-92ae-c7176eedd56d.png)
![image](https://user-images.githubusercontent.com/42404718/95968285-8d204c80-0e0d-11eb-8ee1-2907920d1341.png)

**Comment by Adrian2k** [comment]
Fixing
