### ISSUE TITLE
ULMM, Murmansk: incorrect geometry

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#116]
strange extrusion on western edge bordering finland/norway
![image](https://user-images.githubusercontent.com/42404718/95968990-78908400-0e0e-11eb-9c7d-8a6e9de706d6.png)
![image](https://user-images.githubusercontent.com/42404718/95969039-86460980-0e0e-11eb-81f1-b6bc9d55e87c.png)

**Comment by Adrian2k** [comment]
Fixing
