### ISSUE TITLE
USSV, Ekaterinburg: Incorrect waypoint

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#117]
Same as EGTN, probably due to double coordinate or non-parallel border. 
(see red dot)
![image](https://user-images.githubusercontent.com/42404718/95969406-f6ed2600-0e0e-11eb-81d2-514079a657b8.png)
![image](https://user-images.githubusercontent.com/42404718/95969433-02d8e800-0e0f-11eb-829e-5fad39d1d4aa.png)

**Comment by Adrian2k** [comment]
Fixing
