### ISSUE TITLE
UIII, Irkutsk, invalid geometry

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#118]
Strange parallel border on the eastern edge (see red dot)
![image](https://user-images.githubusercontent.com/42404718/95969681-551a0900-0e0f-11eb-8aab-f068eb964725.png)
![image](https://user-images.githubusercontent.com/42404718/95969699-5c411700-0e0f-11eb-97a1-c2e53a4c2f9d.png)

**Comment by Adrian2k** [comment]
Fixing
