### ISSUE TITLE
TEH-7, Incorrect geometry

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#119]
self intersect, see red dot:
![image](https://user-images.githubusercontent.com/42404718/95969891-97434a80-0e0f-11eb-8173-9f1113235795.png)
![image](https://user-images.githubusercontent.com/42404718/95969919-9f9b8580-0e0f-11eb-98d5-ee27be0ea08c.png)

**Comment by Adrian2k** [comment]
Fixing
