### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by pikachu1992** [vatsimnetwork/vatspy-data-project#12]
Hello,

I am the webmaster at Portugal vACC. I have contributions from one of our members to submit to this project.

However, I'm not sure how to get a _verified GitHub account_ as is stated on the readme file.

Can someone clarify that process?

**Comment by pedro2555** [comment]
I believe someone made it more clear. 7cc1d4a67a1eba37b9b2c18bcd5b2daf2d5a7217
