### ISSUE TITLE
Outdated sectors for Germany (EDMM/EDGG/EDWW and EDUU/EDYY)

### ISSUE THREAD

**Issue by Lotus3xiG3** [vatsimnetwork/vatspy-data-project#122]
[Sektorübersicht.pdf](https://github.com/vatsimnetwork/vatspy-data-project/files/5383335/Sektorubersicht.pdf)

These are the actual german sectors right now. I will work on them together with @NelisV.

**Comment by NelisV** [comment]
![image](https://user-images.githubusercontent.com/42404718/96098840-e1413480-0ed2-11eb-8524-b28f1e97fd8d.png)
Redesign in progress

**Comment by Lotus3xiG3** [comment]
I will ask LOVV (Vienna) about the border around LOWI/Innsbruck as this does not reflect the current situation either.

**Comment by prryplatypus** [comment]
@NelisV Confirm this was fixed in #123?

**Comment by NelisV** [comment]
Jup, can be closed 👍
