### ISSUE TITLE
Borders between Israel <-> Cyprus, Saudi Arabia and Egypt not synced

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#133]
![image](https://user-images.githubusercontent.com/42404718/96861563-912f1880-1464-11eb-99f7-204b22545298.png)

**Comment by nakoale** [comment]
@NelisV what program do you use for vatspy coordinates?

**Comment by NelisV** [comment]
[QGIS](https://qgis.org/en/site/) combined with a parser i wrote. It's still quite a mess tho, can't release it yet.
