### ISSUE TITLE
Subdivisions OMAE

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#135]
As requested by @chrissKLO 
ACC South East = OMAE_R_CTR
![image](https://user-images.githubusercontent.com/42404718/97081675-3b917200-1604-11eb-972a-8055dc63e4e7.png)

**Comment by chrissKLO** [comment]
Looks good to me!

**Comment by chrissKLO** [comment]
Might wanna hold off this for a little while till I update you. They recently changed their ACC sectors. I will message you with the information later on.

**Comment by chrissKLO** [comment]
![OMAE Sectors](https://media.discordapp.net/attachments/473462542430109696/792346466899329064/UAELowSectors.png)

**Comment by NelisV** [comment]
perfect, i'll work on this one 👌

**Comment by chrissKLO** [comment]
Could this be done in time for the next AIRAC Update when possible? Thanks!

**Comment by NelisV** [comment]
As discussed, these are event only positions which we can not support with the current file format.
