### ISSUE TITLE
LIMM covers LIPP as well

### ISSUE THREAD

**Issue by nakoale** [vatsimnetwork/vatspy-data-project#137]
![Screenshot_9](https://user-images.githubusercontent.com/19704019/97110357-71f0ef00-16e1-11eb-8b09-bda938aa0a28.png)

**Comment by Connorseds2002** [comment]
should be fixed as of #154

**Comment by Connorseds2002** [comment]
has now been fixed as of the latest update

**Comment by nakoale** [comment]
I put the new update but still LIPP is not covered by LIMM. missing something?

**Comment by nakoale** [comment]
probably you need to combine the 2 FIR boundaries into One inside the FIRboundaries.dat

**Comment by Connorseds2002** [comment]
@nakoale thanks I have fixed the problem now and should be fine 
![image](https://prnt.sc/vkd2s2)

**Comment by Connorseds2002** [comment]
should be fixed as of #155 with the correct data

**Comment by nakoale** [comment]
yet it doesnt show LIPP as part of LIMM.

**Comment by Connorseds2002** [comment]
> yet it doesnt show LIPP as part of LIMM.

@nakoale this is bring review by the VATITA staff and should be updated soon

**Comment by nakoale** [comment]
any update?

**Comment by Adrian2k** [comment]
Fixed in #283
