### ISSUE TITLE
Newest version throws an error

### ISSUE THREAD

**Issue by matthewpow** [vatsimnetwork/vatspy-data-project#138]
The newest version (most recent merge was 2 hours ago) throws an unhandled exception: The given key was not present in the dictionary.

Attached are text files with the two errors, one given while opening and one after clicking "Continue".
[new 1.txt](https://github.com/vatsimnetwork/vatspy-data-project/files/5435618/new.1.txt)
[new 2.txt](https://github.com/vatsimnetwork/vatspy-data-project/files/5435619/new.2.txt)

**Comment by Adrian2k** [comment]
Works fine for me.
This error usually comes when the VATSpyConfig.xml file is corrupt, this file includes your vatspy settings. If you delete this file it will automatically regenerate with default settings.

**Comment by matthewpow** [comment]
> Works fine for me.
> This error usually comes when the VATSpyConfig.xml file is corrupt, this file includes your vatspy settings. If you delete this file it will automatically regenerate with default settings.

Silly me... I was messing with that file trying to see if it was corrupted and didn't even think to just refresh it. Thanks!
