### ISSUE TITLE
Berlin airports.

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#140]
EDDB probably should be renamed to Berlin-Brandenburg?
EDBB should be removed as an airport entry and instead be put in as a IATA/controllercode in EDDB as their placed on the same placed.

EDBB is not an airport, just a logon for Berlin Approach.

**Comment by nakoale** [comment]
need to see how the RG bremen will use it first. if they want to keep it as EDBB_APP in order to control TXL as well even if it's closed in real life (it's not on vatsim).

**Comment by NelisV** [comment]
@Lotus3xiG3 might want to weigh in.

**Comment by Lotus3xiG3** [comment]
EDDB can be renamed to Berlin-Brandenburg.
EDBB_APP will be kept for now. 
EDDT (after 8th of november) and EDDI (if it still is in the files) can be deleted. These airport will not be controlled anymore.

**Comment by Adrian2k** [comment]
EDBB can be added as a controller code to EDDB, no need to have EDBB as an airport entry,

`EDDB|Berlin-Schonefeld|52.378611|13.520556|EDBB|EDWW|0`

**Comment by prryplatypus** [comment]
Fixed in #141
