### ISSUE TITLE
NY_FSS missing

### ISSUE THREAD

**Issue by qwertyplanes** [vatsimnetwork/vatspy-data-project#152]
no NY_FSS. frequency 130.000

**Comment by Connorseds2002** [comment]
#153 Fixed with this update

**Comment by Connorseds2002** [comment]
@qwertyplanes Thanks for passing this on to us and will be fixed soon

**Comment by amosngSP** [comment]
It didn't go missing, but it was misplaced under KZNY instead, probably because of the NY_ prefix. I did try to make KZWY Oceanic, then put its precedence in the file before KZNY, the rest of the KZNY CTR controllers dont appear at all

**Comment by Connorseds2002** [comment]
Thanks when I looked at there website there position that I could see on there website that there ocianic part was using _FSS at the end instead of the one in the data file
