### ISSUE TITLE
Naha Control changed to Kobe Control

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#157]
NOTAM from VATJPN: https://forums.vatsim.net/topic/22236-notice-of-changes-in-naha-vacc-operation/

FIR Name changed from RORG to RJBG. Callsign "Kobe Control".

RJJJ Oceanic (If it has not been updated), is now RJTG Oceanic (RJTG_FSS).

**Comment by Connorseds2002** [comment]
This should be fixed as of #158 thanks @amosngSP

**Comment by Connorseds2002** [comment]
Fixed #158
