### ISSUE TITLE
Misleading Readme - e-mailing the changes

### ISSUE THREAD

**Issue by ThaweK** [vatsimnetwork/vatspy-data-project#163]
> Please send an email to, or have your Region, Division, or FIR/ARTCC Leadership send an email from your/their staff Region, Division, or FIR/ARTCC linked e-mail account with your GitHub username to a.long (at) vatsim.net. 

You are not responding via official e-mails to the sent changes. You are only reacting to PR, so this is misleading.

**Comment by prryplatypus** [comment]
We're currently working on a contribution policy for this repo which will replace the instructions in the readme file. In the meantime please drop me an email to n.perez(at)vatsim.net if you have any concerns.
