### ISSUE TITLE
UMKK - borders adjustment

### ISSUE THREAD

**Issue by DoubleWhisky** [vatsimnetwork/vatspy-data-project#166]
I am not advanced user of GitHub and I hope this channel is acceptable.
Below I've attached fixed borders of Kaliningrad FIR. Adjusted to neighboring airspaces. Especially Polish, Lithuanian and Swedish. If there's any tiny discrepancy between EPWW and UMKK over Baltic Sea it will be fixed by PLVACC on EPWW side of the border.

@NelisV thanks for converter!

UMKK|0|0|53|54.316364|17.550000|56.095000|22.881053|55.205682|20.215527
54.458333|19.641667
54.603333|19.406667
55.85|17.55
56.095278|18.018611
55.283333|20.95
55.2457|21.276489
55.284775|21.354272
55.290681|21.388639
55.252811|21.434189
55.231011|21.445583
55.209853|21.482778
55.194489|21.502081
55.189239|21.521603
55.198719|21.575375
55.187889|21.627361
55.127944|21.748647
55.120014|21.821567
55.098675|21.849992
55.075644|21.952064
55.085522|22.034539
55.061675|22.0371
55.026189|22.071044
55.037169|22.131314
55.050508|22.141711
55.063564|22.232322
55.056661|22.419456
55.047878|22.469069
55.071814|22.580897
55.020236|22.612461
54.991069|22.683592
54.942086|22.767058
54.911217|22.795242
54.902683|22.845656
54.867767|22.849172
54.8396|22.871083
54.797375|22.881053
54.7743|22.851925
54.740783|22.772008
54.709389|22.732692
54.658203|22.750967
54.640572|22.751428
54.603439|22.697614
54.570347|22.70685
54.537567|22.689919
54.498961|22.694508
54.447422|22.730336
54.401531|22.757261
54.402378|22.798136
54.393714|22.816625
54.365253|22.787792
54.3601|22.631292
54.316667|21.466667
54.458333|19.641667

**Comment by NelisV** [comment]
@DoubleWhisky please have a look at the Draft PR, there are still some misaligned borders on the southern end. although those might be fixed in the EPWW update #160
