### ISSUE TITLE
KZWY removed

### ISSUE THREAD

**Issue by kmoberg** [vatsimnetwork/vatspy-data-project#167]
Hi, 

Since the email listed in the repo haven't responded and I don't have access to PRs to this repo, reference commit 2c601e97de95923f18d022dbbd5bec80b58ab61b #153 . This is wrong. KZWY is its own sector and does NOT belong to New York Center. We have a commit ready which will fix these borders, as soon as we can get permissions to the repo.

Karl,
NYARTCC ATM

**Comment by prryplatypus** [comment]
Hey @kmoberg, could you drop myself an email to n.perez(at)vatsim.net, please?

**Comment by kmoberg** [comment]
@prryplatypus We did, @ajying sent a couple of days ago.

**Comment by prryplatypus** [comment]
I haven't got any emails. It was probably sent to the email that there usually was on the README file (I've just updated that).

**Comment by ajying** [comment]
I've just forwarded the email we sent.

**Comment by prryplatypus** [comment]
Received :)

**Comment by Adrian2k** [comment]
Resolved in #168
