### ISSUE TITLE
ENXN withdrawn - ENTX added

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#169]
ENXN withdrawn in AIRAC 2012.
ENTX added in AIRAC 2012.

Ref: eAIP Norway - AMDT log
https://ais.avinor.no/no/AIP/View/95/2020-11-05-AIRAC/html/index-en-GB.html

"GEN 2.4 | Norway FIR renamed to Polaris FIR. ENTX added. ENXN WD."

**Comment by prryplatypus** [comment]
Fixed in #171
