### ISSUE TITLE
CZQM and CZQX are separated by incorrect geometry

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#175]
A polygon is used as a line to split these 2 sectors, the correct way to do it would be to split it into 2 complete polygons to overlay the 2 sectors (CZQM and CZQX) that already cover both sectors. 

![image](https://user-images.githubusercontent.com/42404718/99907516-6e9b5400-2cdd-11eb-800d-37ce1ddd5083.png)
So turn this:
![image](https://user-images.githubusercontent.com/42404718/99907526-79ee7f80-2cdd-11eb-9fad-3dc34da940db.png)
Into this:
![image](https://user-images.githubusercontent.com/42404718/99907577-d356ae80-2cdd-11eb-87e6-4182f6f97d85.png)

**Comment by ajying** [comment]
Reposting from the other thread on this, this would also be a good opportunity to fix the display of the Moncton, Gander, and Montreal sectorization (http://czqm.ca/Airspace.aspx). I have some contacts for the FEs there that I can reach out to to see if they're interested in resolving that.

**Comment by ajying** [comment]
This can be closed now that #221 has been merged
