### ISSUE TITLE
GCCA_APP not displaying

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#176]
![image](https://user-images.githubusercontent.com/35482228/99908417-d902c300-2ce2-11eb-90b0-ce077dc89087.png)

Have ATIS setup at GCRR.

**Comment by prryplatypus** [comment]
This approach covers both GCRR and GCFV.

**Comment by Adrian2k** [comment]
> This approach covers both GCRR and GCFV.

Do you know which airport the circle should be on?

**Comment by prryplatypus** [comment]
Either both or none 😂

**Comment by Adrian2k** [comment]
> Either both or none 😂

Not possible 😢

**Comment by prryplatypus** [comment]
GCFV it is then after discussion with VACC staff

**Comment by Adrian2k** [comment]
Resolved in #184
