### ISSUE TITLE
ESOS and ESMM different sectors

### ISSUE THREAD

**Issue by nakoale** [vatsimnetwork/vatspy-data-project#177]
when ESOS is online should cover both ESOS and ESMM but it is shown as ESMM is online as well. Probably the line in the middle should not be lighted when ESOS is online. The same issue as with Gander and Moncton

**Comment by Adrian2k** [comment]
@NelisV want to take this one? I can approve changes on behalf of Scandinavia.

**Comment by NelisV** [comment]
I'll dive in 👌

**Comment by nakoale** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/19704019/99996186-10956c00-2dc4-11eb-8025-4a236828c384.png)

**Comment by nakoale** [comment]
and by the way im not pretty sure if this is ESMM sector. i think it's totally different in their sectors.

**Comment by Adrian2k** [comment]
ESOS covers the whole FIR when ESMM is offline.
ESMM sector has many altitude splits, the one they wanted on vatpy is based on the sectors where ESMM covers to GND to show what airports ESMM covers.

**Comment by Adrian2k** [comment]
I think I misunderstood the issue first.

There is no issues with Sweden, definitions are correct.
When ESMM is offline, ESOS_1_CTR will take ownership of all ESMM sectors. It has always been like this.

This is also covered in their controller info.

**Comment by nakoale** [comment]
im just saying the ESMM should be lighted if ESOS is online. take a look at LGGG when it is online it covers LGMD as well. the latter is not lighted. when LGMD goes online it will be lighted as a separate sector. maybe i didnt make it clear.

**Comment by Adrian2k** [comment]
ESMM should be lighted up because ESOS covers that area.
The ICAO Code ESMM is not lighted up, since its a extension sector when only ESOS is online.
