### ISSUE TITLE
Duplicate vertexes

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/vatspy-data-project#188]
![image](https://user-images.githubusercontent.com/42404718/100023661-a988af00-2de5-11eb-9e03-f0f26c27539b.png)

**Comment by Adrian2k** [comment]
@dsolesvik have any of your PR's resolved these, or only unalliged borders?

**Comment by dsolesvik** [comment]
> @dsolesvik have any of your PR's resolved these, or only unalliged borders?

Some, but not sure about all. I would like to wait for all current PRs to be merged, before continuing with any changes, to stay uo-to-date so I will check once they are approved. Feel free to close this, I can come back to this image to reference this.
