### ISSUE TITLE
Mexico FIRs missing

### ISSUE THREAD

**Issue by XCSWxcsw** [vatsimnetwork/vatspy-data-project#195]
![image](https://user-images.githubusercontent.com/40914896/100268807-dd82e200-2f55-11eb-9a94-91d2930420eb.png)

It seems that the full Mexico FIRs are missing. Can anyone fix it?

**Comment by Adrian2k** [comment]
It does not seem like you are using the correct datafiles, have you updated VATSpy to the latest version?

![image](https://user-images.githubusercontent.com/35482228/100269139-58e49380-2f56-11eb-82a0-6d28d87023a3.png)

**Comment by XCSWxcsw** [comment]
I'v download from here

![image](https://user-images.githubusercontent.com/40914896/100269796-664e4d80-2f57-11eb-9b63-45cabaa59626.png)

**Comment by Adrian2k** [comment]
Yes, that's the one I have, and that is also the one you automatically get if you have updated your VATSpy to the latest beta version.
Mexico FIR is included and has been included for a very long time in these files.

http://www1.metacraft.com/VATSpy/#download If you download the latest beta and install it you should also get these files.

**Comment by XCSWxcsw** [comment]
![image](https://user-images.githubusercontent.com/40914896/100270647-a95cf080-2f58-11eb-8240-8bff530a38cc.png)
 I got that now! thanks!
