### ISSUE TITLE
London Control areas don't match the individual areas?

### ISSUE THREAD

**Issue by PaulWalkerUK** [vatsimnetwork/vatspy-data-project#199]
At the moment, it looks like the only London Control area logged on is LON_C_CTR. Using the latest release from this project, all of EGTT is highlighted. Since there does seem to be an area marked for EGTT-C on the map, I was expecting to see just that area highlighted?

Is this something that's possible to fix, am I misunderstanding how this works or is it just a limitation of what this project can achieve without updating the actual source code of the VAT-Spy itself?

![image](https://user-images.githubusercontent.com/5160018/100666674-451f9f80-3351-11eb-8093-ede3772a5ee2.png)

**Comment by Adrian2k** [comment]
VATSpy does only read upto the first underscore, so if LON_C_CTR is online, VATSpy will only see LON_CTR.
The reason why the "EGTT-C" sectors are added is so you can see where they are on the map.
