### ISSUE TITLE
VIPT and VOPN have bogus latitudes/longitudes

### ISSUE THREAD

**Issue by marvk** [vatsimnetwork/vatspy-data-project#203]
# [VIPT](https://en.wikipedia.org/wiki/Pantnagar_Airport) (Pantnagar Airport)

Longitude > 90

Actual position: 29.032222, 79.474167

Also, VIPT doesn't seem to serve Agartala, which is served by ([VEAT](https://en.wikipedia.org/wiki/Maharaja_Bir_Bikram_Airport)). Instead, it serves Pantnagar.

https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/VATSpy.dat#L13515

# [VOPN](https://en.wikipedia.org/wiki/Sri_Sathya_Sai_Airport) (Sri Sathya Sai Airport)

Latitude > 180.

Actual position: 14.149167, 77.791111

https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/VATSpy.dat#L13635

**Comment by Adrian2k** [comment]
Resolved in #225
