### ISSUE TITLE
7ea2e22 introduced self intersection on KZNY non-oceanic FIR

### ISSUE THREAD

**Issue by marvk** [vatsimnetwork/vatspy-data-project#206]
Commit 7ea2e224f2f94dcfe13620a1ebacc28d76e9a64c introduced a self intersection on the KZNY non-oceanic polygon near the following point:

https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/FIRBoundaries.dat#L8940

![](https://i.imgur.com/TAxCkLk.png)

**Comment by NelisV** [comment]
@kmoberg could you consider a fix for this?

**Comment by kmoberg** [comment]
@NelisV @marvk We're on it!

**Comment by kmoberg** [comment]
Fixed in PR #207 @NelisV
