### ISSUE TITLE
Two entries for Sarajevo/Butmir airport

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#212]
VATSpy currently has two entries for Sarajevo/Butmir airport in Bosnia-Herzegovina: LQSA and LQBU (see attached screenshot). From my knowledge there should be only one code (LQSA).

![Sarajevo_Butmir](https://user-images.githubusercontent.com/74152765/102020576-4ea9fe00-3d7a-11eb-919c-a1d255858e2d.jpg)

**Comment by Adrian2k** [comment]
According to Eurocontrol they are 2 different airports.


LQSA | BOSNIA AND HERZEGOVINA | SARAJEVO INTERNATIONAL AIRPORT | LQSA | SJJ | AD |   | 434928.10N | 0181954.36E | WGE | SARAJEVO

LQBU	BOSNIA AND HERZEGOVINA	SARAJEVO/BUTMIR	LQBU	 	AD	 	434845N	0182030E	WGE	SARAJEVO



So this is where the airport appeared from (an earlier Eurocontrol import).
However I can not find any information about this ICAO, neither does it seem to be existing in the Bosnia and Herzegovina AIP, so I will remove it.

**Comment by Adrian2k** [comment]
Resolved in #225
