### ISSUE TITLE
MYNN Nassau FIR PROVO Sector Missing

### ISSUE THREAD

**Issue by Jeeveegee** [vatsimnetwork/vatspy-data-project#216]
When MYNN_CTR is online the PROVO Sector is missing and does not show up in VATSPY. This sector is covered by MYNN from SFC to 17000ft and above that it's controlled by Miami Oceanic (if both are online, if not, the online sector controls from SFC to FL600).

**Comment by Adrian2k** [comment]
Fixed in #217
