### ISSUE TITLE
ADD gmmm centers splits

### ISSUE THREAD

**Issue by obb12** [vatsimnetwork/vatspy-data-project#22]
GMMM_E_CTR  covering north eastern Marocco

GMMM_S_CTR covering southern Marocco
GMMM_W_CTR covering western Marocco (airways UN866/UN873/UN858/UN857)
GMMO_CTR overing airways UN866 and UN873 within Casablanca FIR

**Comment by obb12** [comment]
https://usermanual.wiki/Pdf/EuroscopeManual.497033894/asset-ab.png if someone knows how to add them

**Comment by luke11brown** [comment]
We need coordinate data, rather than just a picture.

**Comment by obb12** [comment]
GMMM_CTR:Casablanca Radar:125.500:MM::GMMM:CTR:::4201:4277:N030.59.00.000:W010.00.00.000:N033.45.00.000:W004.00.00.000:N034.39.00.000:E009.31.00.000
GMMM_E_CTR:Casablanca Radar:125.100:MME:E:GMMM:CTR:::4201:4277:N033.45.00.000:W004.00.00.000
GMMM_S_CTR:Casablanca Radar:126.700:MMS:S:GMMM:CTR:::4201:4277:N030.59.00.000:W010.00.00.000
GMMM_W_CTR:Casablanca Radar:128.800:MMW:W:GMMM:CTR:::4201:4277:N033.19.00.000:W011.35.00.000
GMMN_APP:Mohammed V Approach:119.900:MNA::GMMN:APP:::4201:4277
GMMN_TWR:Mohammed V Tower:118.500:MNT::GMMN:TWR:::4201:4277
GMMO_CTR:Casablanca Radar:124.500:MO::GMMO:CTR:::4201:4277:N033.19.00.000:W011.35.00.000
Heres the coordinates from sector file

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by luke11brown** [comment]
That's just the center points, we need sector boundaries.

**Comment by obb12** [comment]
Gmmo_S

COORD:N033.11.25.000:W013.58.47.000
COORD:N032.44.22.000:W012.26.05.000
COORD:N030.43.48.000:W014.02.52.000
COORD:N032.44.22.000:W012.26.05.000
COORD:N030.43.48.000:W014.02.52.000
COORD:N031.30.00.000:W015.45.00.000
COORD:N033.11.25.000:W013.58.47.000
COORD:N032.15.00.000:W014.37.00.000
COORD:N032.04.46.256:W014.46.05.106
COORD:N031.52.59.514:W014.58.17.106
COORD:N031.42.57.090:W015.12.27.273
COORD:N031.34.53.212:W015.28.14.972
COORD:N031.30.00.000:W015.45.00.000

GMMO_N
COORD:N035.58.00.000:W009.37.46.000
COORD:N033.11.23.000:W011.32.22.000
COORD:N033.11.23.000:W011.32.22.000
COORD:N032.44.22.000:W012.26.05.000
COORD:N033.11.25.000:W013.58.47.000
COORD:N032.44.22.000:W012.26.05.000
COORD:N035.58.00.000:W010.44.00.000
COORD:N035.58.00.000:W012.00.00.000
COORD:N035.58.00.000:W010.44.00.000
COORD:N035.58.00.000:W009.37.46.000
This position is usually bandboxed



Gmmn_N usually online covering whole of morroco either as gmmm or gmmm_N
COORD:N033.38.50.000:W006.53.37.000
COORD:N033.37.23.550:W006.53.13.046
COORD:N033.31.08.154:W006.52.41.060
COORD:N033.24.53.209:W006.53.19.893
COORD:N033.18.47.929:W006.55.08.340
COORD:N033.13.01.259:W006.58.03.511
COORD:N033.11.51.000:W006.58.54.000
COORD:N034.02.24.000:W007.10.23.000
COORD:N033.59.28.640:W007.06.32.452
COORD:N033.54.41.030:W007.01.39.845
COORD:N033.49.18.855:W006.57.45.585
COORD:N033.43.30.141:W006.54.55.317
COORD:N033.38.50.000:W006.53.37.000
COORD:N033.04.25.000:W007.05.05.000
COORD:N033.07.41.658:W007.02.00.919
COORD:N033.11.51.000:W006.58.54.000
COORD:N033.11.41.000:W008.22.00.000
COORD:N033.07.41.658:W008.19.14.821
COORD:N033.02.56.903:W008.14.21.129
COORD:N032.58.53.901:W008.08.38.416
COORD:N032.55.38.534:W008.02.15.079
COORD:N032.53.15.522:W007.55.20.440
COORD:N032.51.48.312:W007.48.04.533
COORD:N032.51.19.007:W007.40.37.870
COORD:N032.51.48.312:W007.33.11.207
COORD:N032.53.15.522:W007.25.55.300
COORD:N032.55.38.534:W007.19.00.661
COORD:N032.58.53.901:W007.12.37.324
COORD:N033.02.56.903:W007.06.54.611
COORD:N033.04.25.000:W007.05.05.000
COORD:N033.11.41.000:W008.22.00.000
COORD:N033.13.01.259:W008.23.12.229
COORD:N033.18.47.929:W008.26.07.400
COORD:N033.24.53.209:W008.27.55.847
COORD:N033.31.08.154:W008.28.34.680
COORD:N033.37.23.550:W008.28.02.694
COORD:N033.43.30.141:W008.26.20.423
COORD:N033.49.18.855:W008.23.30.155
COORD:N033.54.41.030:W008.19.35.895
COORD:N033.59.28.640:W008.14.43.288
COORD:N034.03.34.496:W008.08.59.492
COORD:N034.06.52.438:W008.02.33.008
COORD:N034.09.17.494:W007.55.33.466
COORD:N034.10.46.016:W007.48.11.381
COORD:N034.11.15.773:W007.40.37.870
COORD:N034.10.46.016:W007.33.04.359
COORD:N034.09.17.494:W007.25.42.274
COORD:N034.06.52.438:W007.18.42.732
COORD:N034.03.34.496:W007.12.16.248
COORD:N034.02.24.000:W007.10.23.000

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by obb12** [comment]
closed
