### ISSUE TITLE
SAM_S_FSS is missing

### ISSUE THREAD

**Issue by marvk** [vatsimnetwork/vatspy-data-project#222]
`SAM_S_FSS` (frequency 134.700) with the following ATIS has no mapping:

    SUDAMERICA CONTROL - EN PRUEBAS SUEO - SAEZ - SAME - SAVC - SCEZ - SCTZ - SCCZ FL245 AND ABOVE

Might this be a missing UIR?

**Comment by Adrian2k** [comment]
It cant be resolved due to how VATSpy works.

There are 4 different SAM sectors that all covers different FIRs.

**Comment by marvk** [comment]
Oh, so I assume they are all called `SAM_S_FSS`? If so please disregard the following, but if not, for example if there is `SAM_S_FSS`, `SAM_N_FSS` and so on, shouldn't it be possible to add them as UIRs distinguished by their infix? After all, there are, for example different `RU` sectors or `GULF` sectors that differ by infix.

**Comment by Adrian2k** [comment]
VATSpy only reads until the first underscore.

**Comment by Adrian2k** [comment]
https://fss.vatsa.net/

**Comment by marvk** [comment]
Forgive my ignorance, but there is `ASEA_N` and `ASEA_S` as well as `GULF`, `GULF_E` and `GULF_W`. Are they non-functional, since they contain an underscore?

**Comment by Adrian2k** [comment]
I have not seen ASEA sectors online, but I have seen GULF.
GULF_FSS, GULF_E_FSS, GULF_W_FSS etc will all display the same area when online.

The issue with SAM is that none of the sectors cover the same area.

**Comment by marvk** [comment]
But the different definitions exist for GULF_E and GULF_W:

https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/VATSpy.dat#L18297
https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/VATSpy.dat#L18298
https://github.com/vatsimnetwork/vatspy-data-project/blob/9c4d2977ae4a625ba43485ab382fe555006185f2/VATSpy.dat#L18299

Will they all display `GULF` regardless of the infix? If so, would it not be consistent to add the `SAM_N`, `SAM_E`, `SAM_S` and `SAM_W` UIRs into the datafile without a `SAM`.

> I have not seen ASEA sectors online, but I have seen GULF.

Incidentally, `ASEA` was online today!

**Comment by Adrian2k** [comment]
There are different definitions for GULF, but they do not work.

As I said VATSpy only reads upto the first underscore.

GULF_E_FSS = GULF ICAO and FSS station type for VATSpy.

**Comment by Adrian2k** [comment]
Adding a definition for SAM_S for example has no effect. I specifically tested this out earlier when SAM was reported missing.

**Comment by marvk** [comment]
I get that they don't work in VATSpy, but wouldn't adding the missing sectors make the data set more complete nontheless? After all, this data set is, as far as I can see, also supposed to serve as a general data set for VATSim map data, since it is [available via the VATSim API.](https://api.vatsim.net/api/#tag/map_data)

**Comment by Adrian2k** [comment]
Resolved as requested in #225 
Will not have any effect with the current version of VATSpy
