### ISSUE TITLE
Puerto Montt FIR (SCTZ) typo & wrong callsign

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#223]
Should be written "Puerto Montt" not "Puerto Mont".
Furthermore, the callsign is not correctly displayed (should be "Puerto Montt Radar" not "Puerto Montt Center").

![Puerto_Montt_SCTZ](https://user-images.githubusercontent.com/74152765/103157191-cfbcb880-47b0-11eb-884a-9e348003f140.jpg)

![puerto_montt_2](https://user-images.githubusercontent.com/74152765/103157192-d4816c80-47b0-11eb-96a9-ed55a3f43542.jpg)

**Comment by Adrian2k** [comment]
Resolved in #225
