### ISSUE TITLE
Q: Is there any chance to change Ukraine Radar description message?

### ISSUE THREAD

**Issue by megazloj** [vatsimnetwork/vatspy-data-project#242]
![image](https://user-images.githubusercontent.com/7577925/105328746-0b447a00-5bd9-11eb-8c59-1696ea67a184.png)
Currently, it displays for each of the five FIRs "Covers UKxx above FL245". Actually, UKR_CTR covers GND-FL660 if local CTR is offline. I couldn't find this in the data files, how it can be changed?

**Comment by Adrian2k** [comment]
You can make a UKR FIR around all the 5 Ukranians FIR like this:
![image](https://user-images.githubusercontent.com/35482228/105330626-cfa6b180-5bd2-11eb-9f05-b718528e2223.png)

This is at least how ADR_CTR has resolved it.

**Comment by megazloj** [comment]
> You can make a UKR FIR around all the 5 Ukranians FIR like this:
> ![image](https://user-images.githubusercontent.com/35482228/105330626-cfa6b180-5bd2-11eb-9f05-b718528e2223.png)
> 
> This is at least how ADR_CTR has resolved it.

Will try that. Thanks Adrian!
