### ISSUE TITLE
London sector splits

### ISSUE THREAD

**Issue by CalMC03** [vatsimnetwork/vatspy-data-project#25]
My FIR boundaries are now much more accurate, thank you! However active centre controllers still appear to be in the same position.
(eg. London Control which has many sectors) 
As you can see in the image, LON_N_CTR is the only London sector online however even though the London North FIR is labelled, VATSPY is still showing it covering the whole of London.
How do i fix this?
![image](https://user-images.githubusercontent.com/62405690/77119799-1b2a8500-6a2f-11ea-8216-c5bdf24f9de6.png)

**Comment by CalMC03** [comment]
( The black line indicates the sector that should be displayed as being online)

**Comment by kieranharvey** [comment]
I have wondered this too, would be great to find out why it does this.

**Comment by kusterjs** [comment]
You need to define the are for LON_N, you may submit an appropriate pull request then.

**Comment by kye-taylor** [comment]
So I've had a look at this:
These positions have been defined within the VATSpy.dat file

`EGTT|London|LON|EGTT`
`EGTT-C|London ACC (Central) - London|LON_C|EGTT-C`
`EGTT-C|London ACC (Central) - London|LON_E|EGTT-C`
`EGTT-C|London ACC (Central) - London|LTC_N|EGTT-C`
`EGTT-C|London ACC (Central) - London|LTC_NW|EGTT-C`
`EGTT-N|London ACC (North) - London|LON_N|EGTT-N`
`EGTT-N|London ACC (North) - London|MAN|EGTT-N`
`EGTT-N|London ACC (North) - London|MAN_E|EGTT-N`
`EGTT-S|London ACC (South) - London|LON_S|EGTT-S`
`EGTT-S|London ACC (South) - London|LON_D|EGTT-S`
`EGTT-S|London ACC (South) - London|LTC_S|EGTT-S`
`EGTT-S|London ACC (South) - London|LTC_SE|EGTT-S`
`EGTT-S|London ACC (South) - London|LTC_SW|EGTT-S`
`EGTT-SC|London ACC (South-Central) - London|LON_SC|EGTT-SC`
`EGTT-SC|London ACC (South-Central) - London|LTC|EGTT-SC`
`EGTT-W|London ACC (West) - London|LON_W|EGTT-W`

From testing, it seems VATSPY doesn't take into account anything after the "_" which I suspect is for removing the _CTR.  This would also explain why Austriallas sectors splits work as the use a "-" ie: "BN-DOS_CTR"
I don't think there is anything that could be done about this, unless the backend code gets changed.

**Comment by nepetadosmil** [comment]
Yep, I believe that is indeed how VATSPY works.

**Comment by Adrian2k** [comment]
That is how vatspy works, I have always believed that LON_N and such gets added so people atleast can see where those sectors belong in relation to their position on vatspy.
