### ISSUE TITLE
Scottish TC Antrim Sector in wrong position

### ISSUE THREAD

**Issue by fcooper94** [vatsimnetwork/vatspy-data-project#256]
STC_A_CTR is a lower sector Scottish sector that covers Northern Ireland. (Below FL245)

![image](https://user-images.githubusercontent.com/16825107/106316413-95897f80-6264-11eb-86e4-976c24d84d53.png)

SCO_R_CTR is above it (Above FL245)

**Comment by fcooper94** [comment]
Here is the defined position from the UK Sector File 2021/01

Scottish Antrim             S999.00.00.000 E999.00.00.000 S999.00.00.000 E999.00.00.000
                            N055.07.49.000 W005.06.23.000 N054.57.14.000 W005.15.30.000 ;Ant_WCoast-Rat
                            N054.57.14.000 W005.15.30.000 N054.54.17.000 W005.29.59.000
                            N054.54.17.000 W005.29.59.000 N054.50.30.000 W006.24.41.000
                            N054.50.30.000 W006.24.41.000 N054.49.48.686 W006.26.29.498
                            N054.49.48.686 W006.26.29.498 N054.49.04.685 W006.28.00.221
                            N054.49.04.685 W006.28.00.221 N054.48.16.895 W006.29.23.982
                            N054.48.16.895 W006.29.23.982 N054.47.25.664 W006.30.40.141
                            N054.47.25.664 W006.30.40.141 N054.46.29.597 W006.31.48.122
                            N054.46.29.597 W006.31.48.122 N054.45.30.913 W006.32.47.412
                            N054.45.30.913 W006.32.47.412 N054.44.29.465 W006.33.37.567
                            N054.44.29.465 W006.33.37.567 N054.43.25.724 W006.34.18.215
                            N054.43.25.724 W006.34.18.215 N054.42.20.178 W006.34.49.572
                            N054.42.20.178 W006.34.49.572 N054.41.13.327 W006.35.09.870
                            N054.41.13.327 W006.35.09.870 N054.40.05.681 W006.35.20.511
                            N054.40.05.681 W006.35.20.511 N054.38.57.757 W006.35.20.911
                            N054.38.57.757 W006.35.20.911 N054.37.50.718 W006.35.11.829
                            N054.37.50.718 W006.35.11.829 N054.36.43.138 W006.34.51.113
                            N054.36.43.138 W006.34.51.113 N054.35.37.465 W006.34.21.170
                            N054.35.37.465 W006.34.21.170 N054.34.33.551 W006.33.41.491
                            N054.34.33.551 W006.33.41.491 N054.33.31.879 W006.32.52.390
                            N054.33.31.879 W006.32.52.390 N054.32.32.915 W006.31.54.251
                            N054.32.32.915 W006.31.54.251 N054.31.37.106 W006.30.47.521
                            N054.31.37.106 W006.30.47.521 N054.30.44.870 W006.29.32.715
                            N054.30.44.870 W006.29.32.715 N054.29.56.603 W006.28.10.404
                            N054.29.56.603 W006.28.10.404 N054.29.12.667 W006.26.41.215
                            N054.29.12.667 W006.26.41.215 N054.28.33.393 W006.25.05.824
                            N054.28.33.393 W006.25.05.824 N054.27.59.768 W006.23.24.951
                            N054.27.59.768 W006.23.24.951 N054.27.54.443 W006.23.06.078
                            N054.27.54.443 W006.23.06.078 N054.05.30.000 W006.24.38.000
                            N054.05.30.000 W006.24.38.000 N053.55.00.000 W005.30.00.000 ;Ant_EIDW
                            N053.55.00.000 W005.30.00.000 N053.48.17.000 W005.30.00.000
                            N054.30.10.000 W003.35.35.000 N054.32.41.000 W003.30.00.000 ;Gal_Ant
                            N054.32.41.000 W003.30.00.000 N055.06.03.000 W004.14.19.000
                            N055.06.03.000 W004.14.19.000 N055.09.59.022 W004.45.00.736
                            N055.09.59.022 W004.45.00.736 N055.12.14.000 W005.02.34.000
                            N055.12.14.000 W005.02.34.000 N055.09.48.000 W005.04.41.000 ;WCoast-RatW_Ant
                            N055.09.48.000 W005.04.41.000 N055.07.49.000 W005.06.23.000 ;WCoast-Rat_Ant
                            N053.48.47.000 W005.30.00.000 N053.48.13.000 W005.09.51.000 ;MWSA2
                            N053.48.13.000 W005.09.51.000 N054.30.10.000 W003.35.35.000

**Comment by Adrian2k** [comment]
VATSpy can not differentiate between different subsectors.

STC_A (and all other logins starting on STC) already highlights the area EGPX-D.
SCO_R highlights the whole of Scottish FIR, something it has to do because of SCO_CTR covering that area.

If there is any need for changes to be performed here, they need to come from an approved GitHub account within VATUK.

**Comment by Adrian2k** [comment]
@hsugden not sure if you want to have a look on this.

**Comment by hsugden** [comment]
Thanks @Adrian2k 

There is no point us drawing this unless we change the callsign - @jackedwards815 (UK Ops Director) is looking into this as a possibility
