### ISSUE TITLE
Renaming of Norwegian airports - Addition of ENOE

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#258]
Rename to create consistency with AIP Norway - Many of the renames are to add a "/" between city and airport/heliport name. Some incorrectly named, and some capitalisation errors.

Rename:
ENNO - Notodden
ENBA - Barentsburg/Heerodden (Heliport)
ENFJ - Fedje/Hoegden (Heliport)
ENHR - Harstad/Stangnes (Helipad)
ENLG - Stryn/Langset (Helipad)
ENLX - Lorenskog/Akershus University Hospital (Helipad)
ENMK - Mosjoen/Helgeland Hospital (Helipad)
ENMO - Meraker/Oeyan (Airstrip)
ENMP - Molde/Helse Moere og Romsdal Hospital (Helipad)
ENMX - Mo i Rana/Helgeland Hospital (Helipad)
ENNH - Namsos/Helse Nord-Troendelag Hospital (Helipad)
ENRH - Oslo/University Hospital Rikshospitalet (Helipad)
ENSA - Svea
ENSC - Suldal/Sand (Helipad)
ENSJ - Sandnessjoen/Helgeland Hospital (Helipad)
ENSP - Sarpsborg/Oestfold Hospital Kalnes (Helipad)
ENSX - Stavanger/University Hospital (Helipad)
ENTE - Skien/Telemark Hospital (Helipad)
ENTH - Tonsberg/Vestfold Hospital (Helipad)
ENTU - Tromso/University Hospital (Helipad)
ENUH - Oslo/Ullevaal University Hospital (Helipad)
ENVR - Vaeroey (Heliport)
ENWV - Valhall PH (Offshore Helideck)
ENYY - Levanger/Helse Nord-Troendelag Hospital (Helipad)

Addition:
ENOE - Troll Airfield Antarctica
-71.9572222, 2.46666

Not entirely sure which FIR it belongs to since its located in Antarctica.

**Comment by ChrisXPP** [comment]
> Not entirely sure which FIR it belongs to since its located in Antarctica.

FAJO (Johannesburg Oceanic), at least according to the current VATSpy data files
