### ISSUE TITLE
ARP of VGHS wrong

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#262]
![image](https://user-images.githubusercontent.com/40349656/107154728-8ebee300-69af-11eb-9075-32d682325b16.png)
The black cross indicates where the ARP is currently in VATspy. The airport I circled in black is the correct airport.
VGZR is the old identifier for VGHS, so it may be removed.

As per AIP, the ARP should be: 235036.05N 0902352.02E (Centre of the runway)
http://www.caab.gov.bd/aip/aerodromes/adall.pdf (page 23)

(For reference, this was the issue on VATspy)
![image](https://user-images.githubusercontent.com/40349656/107154832-f9701e80-69af-11eb-9859-a9d32cee6552.png)

**Comment by amosngSP** [comment]
Addon: Currently the airport at the old VGHS ARP seems to be VGTJ (refer to page 239 on the AIP)
VGTJ ARP: 2346.69N 09022.96E
![image](https://user-images.githubusercontent.com/40349656/107154882-3dfbba00-69b0-11eb-914a-566c983077b6.png)

**Comment by Adrian2k** [comment]
Fixed VGHS, removed VGZR.

VGTJ coordinates did not make sense, there is nothing looking like an airport or helipad where it leads me to.
