### ISSUE TITLE
Wrong floor LFEE_N sector

### ISSUE THREAD

**Issue by Pampah91** [vatsimnetwork/vatspy-data-project#264]
Hello,

The floor of the LFEE_N sector is wrong. The current one is indicated as FL195 and above while it should be 295 and above.

Current situation : 

![](https://i.gyazo.com/c3f8916356544a51105f701b366269a1.png)

**Comment by FrenchGap** [comment]
As ACCFR5 (and I believe one of the approved PRs for the French vACC), I second this issue.
The floor is wrong and should be raised to FL295+
