### ISSUE TITLE
Sector splits don't show up as expected.

### ISSUE THREAD

**Issue by Alaqmaar** [vatsimnetwork/vatspy-data-project#275]
This is probably something under consideration, but I thought I'd bring it up, as it isn't listen on this GitHub from what I see.

This is to do with how Sector Splits VATSpy are shown, although sector splits are listed on VATSpy, when a Sector Split position is online, it will always place it over the entire sector, as seen in the example below.

![image](https://user-images.githubusercontent.com/75083436/109489013-ba5d5680-7a9f-11eb-9f75-c9855d0fa155.png)

**Comment by ChrisXPP** [comment]
That's a known limitation of VATSpy.

In your case it "ignores" the "_SC" in the callsign and thus displays it with the shape of "LON_CTR".

**Comment by Adrian2k** [comment]
As stated by Chris this is a VATSpy limitation. 
The EGTT-SC and similar sectors are there simply to help you understand where LON_SC_CTR is covering on the map.

This is currently not something we can fix with the dataset with the current version of VATSpy, and will therefore not be resolved.
