### ISSUE TITLE
CZUL special approach sector

### ISSUE THREAD

**Issue by Mistadouf** [vatsimnetwork/vatspy-data-project#28]
In CZUL, we have a position that covers both CYOW and CYQB terminal control areas named Capital approach (CPTL_APP). Is there any way to display it on vatspy? I've tried myself to understand the way vatspy identifies special callsigns to match it to a position, but I was only able to display either CYOW or CYQB approach circle, but never both. Seems like as soon as a match is found in the database, vatspy stops searching for another match. Is that correct? Let me know if you have any tips for me.
Thanks

**Comment by gdonohoe** [comment]
Hello,

If I understand your request properly its that you would like a ring to appear around both CYQB and CYOW when CPTL_APP is online.

Unfortunately, this cannot be achieved in VATSPY - you would have to choose between either CYOW  or CYQB to display the ring around.
