### ISSUE TITLE
Make SKED light up SKEC.

### ISSUE THREAD

**Issue by Santiago-1496502** [vatsimnetwork/vatspy-data-project#285]
Make the SKED FIR and the SKEC FIR show both covered when SKED_CTR is online, as SKED_CTR controlls the whole Colombian airspace.

**Comment by harvyandrew** [comment]
Hello Adrian, good afternoon, my name is Harvy Andrew Guzman and I am the director of the Colombian division in VATSUR, my ID is 1432123 and I was the one who sent Santiago to make the request.
Thank you for your collaboration

**Comment by prryplatypus** [comment]
✔️ Confirmed
