### ISSUE TITLE
New Data Format for ATISs

### ISSUE THREAD

**Issue by kolbyd** [vatsimnetwork/vatspy-data-project#29]
VATSIM recently updated the data format for their ATISs and they don't break into sentences anymore.

For example:

Before - 
Thanks for flying with the Winnipeg FIR!
Questions, comments or feedback? We want to hear it!
Visit us at czwg.vatcan.ca.

Now - 
Thanks for flying with the Winnipeg FIR!^Â§Questions, comments or feedback? We want to hear it!^Â§Visit us at czwg.vatcan.ca.

**Comment by nepetadosmil** [comment]
Not related to this repo :)
