### ISSUE TITLE
Malta/Roma delegated airspace

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#290]
See #287 for details.

**Comment by dsolesvik** [comment]
Have Italy staff confirmed that they would like these changes?

**Comment by NelisV** [comment]
Confirmed by ACCIT1:
![image](https://user-images.githubusercontent.com/42404718/147834414-c2b50ea9-e72b-4392-afd7-006dd8507d7e.png)

**Comment by NelisV** [comment]
Received the data from VATITA director. will pick this up for 2202.
