### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by KDPryor** [vatsimnetwork/vatspy-data-project#3]
Hello, I installed your data files in VATSpy today as per the directions. When starting the program now, I get this error:

The following error occurred while attempting to load the data files:
Input string was not in a correct format

**Comment by nepetadosmil** [comment]
Hello @KDPryor!

Could you try with [this FIRBoundaries.dat](https://raw.githubusercontent.com/vatsimnetwork/vatspy-data-project/2a5b4bb620b2b0e7dc9d6cf400daa19631b9f7a4/FIRBoundaries.dat) instead?

If it works then, I might know what is causing it. Please let us know the outcome :)

**Comment by KDPryor** [comment]
That does seem to have solved the problem. Thank you!

**Comment by nepetadosmil** [comment]
@zachbf The 2 lines I added as a comment don't seem to be interpreted as comments. We might want to rollback that commit or maybe get @RossMetacraft to interpret lines starting with ";" as comments in the FIRBoundaries.dat file as well
