### ISSUE TITLE
New Airport WBGK

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#308]
Hello Gents,
Malaysia recently introduced a new airport, effective 22nd April.
The airport ICAO code is being re-used so there is a need to re-align the ICAO identifier in VATSpy.

Reference: https://aip.caam.gov.my/aip/eAIP/2021-04-22-AIRAC/html/eSUP/WM-eSUP-2021-02-en-MS.html

**Comment by Adrian2k** [comment]
So if I understood this correctly, this is the change you want to be implemented?
![image](https://user-images.githubusercontent.com/35482228/115305916-5d108800-a167-11eb-84d3-68493dec4ebf.png)

And the old airport is shut down?

**Comment by Adrian2k** [comment]
@amosngSP  Also, are you a staff member within Malaysia? I can not find you on the verified account list.
Just want to make sure before performing this change, as there could be reasons for the operations team to stick with the old location.

**Comment by amosngSP** [comment]
Hello @Adrian2k 
As far as I know the old airport is uncontrolled, but so far there are no new sceneries for this airport either.
The new airport however will have a Tower and Ground service available, but I will check in with the staff team if they'd like to implement this change.

**Comment by amosngSP** [comment]
Hello!

Just an update, checked back with the staff team and they'd like to update the coordinates to the new airport.
As for my GitHub account approvals, have dropped Nestor an email to approve my account.
