### ISSUE TITLE
VATSSA Africa FSS positions

### ISSUE THREAD

**Issue by dswoodward** [vatsimnetwork/vatspy-data-project#342]
![Africa FSS Map](https://user-images.githubusercontent.com/62430110/124353079-2392d900-dbfc-11eb-909a-1f49ec0d79d7.jpeg)

We are in the process of updating the VATSSA Overland FSS positions. These will be as shown:

AFRW = Green
AFRC = Blue
AFRS = Red

AFRC is already live, with the others going live in the next week (maximum 2 weeks)

Please could these be updated/added?

Thank you!

Dave (VATSSA1)

**Comment by dswoodward** [comment]
Submitted for pull request but pending review.

**Comment by Adrian2k** [comment]
@dswoodward is AFRN/AFRE still in use?

**Comment by dswoodward** [comment]
> @dswoodward is AFRN/AFRE still in use?

That isn’t VATSSA airspace so I don’t know about those. They belong to VATMENA.
