### ISSUE TITLE
Change to CZQO_CTR and EGGX_CTR 

### ISSUE THREAD

**Issue by dsolesvik** [vatsimnetwork/vatspy-data-project#353]
As of Airac 2108, due to the addition of NAT_FSS, we will be fully reverting to the use of CZQO_CTR and EGGX_CTR. If you may, please remove CZQX_FSS and EGGX_FSS, as well as the CZQX DEL positions and please replace them with CZQO_CTR and EGGX_CTR. Approved as Gander Oceanic Operations Director.

**Comment by amosngSP** [comment]
#352 It's already been submitted by Jack Edwards :)

**Comment by dsolesvik** [comment]
For EGGX, but we just wanted to make sure that it is the same for CZQO, as we are doing it for CZQO as well.

**Comment by dsolesvik** [comment]
#355
