### ISSUE TITLE
Rename FIR ICAO

### ISSUE THREAD

**Issue by neliscoet** [vatsimnetwork/vatspy-data-project#36]
Hi,

Please rename FIR FVHA to FVHF and Airport FVHA to FVRG

Also make sure that it is changed in AFRS FSS Station.

Thanks

**Comment by nepetadosmil** [comment]
Please submit a Pull Request with the changes.

**Comment by neliscoet** [comment]
Lol, sorry i thought i did 🤣

**Comment by gdonohoe** [comment]
Pull request #35 fixes this issue.
