### ISSUE TITLE
CZQO-GOTA arrangements

### ISSUE THREAD

**Issue by dsolesvik** [vatsimnetwork/vatspy-data-project#360]
As with similar surrounding Canadian sectors, would it be possible to modify the GOTA to the following, as per our agreements with Moncton/Gander dom?

CZQO-GOTA: Covered by CZQX (thus also by CZQM when consolidated) **above FL290** and covered by CZQO **below FL290**? Thanks, approved by Gander Oceanic staff.

**Comment by Adrian2k** [comment]
Keep in mind that VATSpy is not made for showing level splits between 2 sectors, hence we refrain from approving such requests. GOTA has probably been added earlier either before we became stricter on this or we have not correctly understood this sector.

**Comment by dsolesvik** [comment]
> Keep in mind that VATSpy is not made for showing level splits between 2 sectors, hence we refrain from approving such requests. GOTA has probably been added earlier either before we became stricter on this or we have not correctly understood this sector.

Thanks Adrian. What I wanted to do was something similar to what CZZV currently covers (CZUL SFC-280 / CZQM 290-ABV), where the sector is highlighted when either or both are online, so I wanted to do the same for the GOTA, as that is similar to what CZZV covers. I spoke to Niels and give me a few days and I'll make a pull request with the appropriate requested amendments.

**Comment by dsolesvik** [comment]
#364
