### ISSUE TITLE
VATSPY Crashes after update

### ISSUE THREAD

**Issue by neliscoet** [vatsimnetwork/vatspy-data-project#37]
Hi Guys,

Vatspy crashes after the Harare update.

[https://prnt.sc/s0xwxs](url)

**Comment by nepetadosmil** [comment]
How are you downloading the files?

**Comment by neliscoet** [comment]
Normal download, zip and i tried the bat install and manually. Even did reinstall of vatspy, am i being a nana somewhere? 🤣
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Apr 17, 2020 at 9:02 PM +0400, "Néstor Pérez" <notifications@github.com> wrote:















How are you downloading the files?

**Comment by kieranharvey** [comment]
Just updated to the current, via the manual overwrite and Vat-Spy booted up fine for me.

**Comment by kusterjs** [comment]
No issues here as well.

**Comment by nepetadosmil** [comment]
Closing then. Thanks gents 👍
