### ISSUE TITLE
Add ENOR-S

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#388]
A challenge for @dsolesvik maybe?
ENOR_S_CTR is probably the most used enroute position in Norway these days and since the data is used in other app's than just vatspy, it would be an idea to add ENOR-S as a sector.
It covers ENSV+ENOS+ENBD-S sectors which exists in vatspy today.

**Comment by dsolesvik** [comment]
> A challenge for @dsolesvik maybe?
> ENOR_S_CTR is probably the most used enroute position in Norway these days and since the data is used in other app's than just vatspy, it would be an idea to add ENOR-S as a sector.
> It covers ENSV+ENOS+ENBD-S sectors which exists in vatspy today.

Say less.
