### ISSUE TITLE
EGJA - possible naming inconsistency?

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#403]
Hi,

right now, Alderney airport (EGJA) is named "Alderney - Channel Island" (see attached screenshot).
Compared to the other both Channel Islands' airports (Jersey and Guernsey) that's inconsistent... maybe this should be renamed to simply "Alderney"?

![EGJA](https://user-images.githubusercontent.com/74152765/132999751-de266b6f-ac34-452d-85d1-2eb81bcdeec1.jpg)

**Comment by Adrian2k** [comment]
I will let our UK people comment on this. @hsugden @jackedwards815

**Comment by hsugden** [comment]
Yes, I approve of this change :) @ChrisXPP @Adrian2k
