### ISSUE TITLE
Remove Eurocontrol Islands

### ISSUE THREAD

**Issue by trevorhannant** [vatsimnetwork/vatspy-data-project#405]
As per:

https://forums.vatsim.net/topic/30909-eurocontrol-islands-removal/?tab=comments#comment-176394

...Eurocontrol Islands is now no longer - data can be removed.

**Comment by dsolesvik** [comment]
#404

**Comment by trevorhannant** [comment]
Apologies, looked the other evening and didn't get round to raising this - didn't think to recheck...

**Comment by prryplatypus** [comment]
We'll close this again when we merge the PR!
