### ISSUE TITLE
LFPZ - typo

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#407]
Hi,

there's a typo in the entry for LFPZ airport in France...

![stcyr](https://user-images.githubusercontent.com/74152765/133653850-5e4ad3dd-68ea-4782-b974-f3788e4c0605.jpg)

According the official French AIP (https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_09_SEP_2021/Atlas-VAC/PDF_AIPparSSection/VAC/AD/AD-2.LFPZ.pdf) this should rather be "St Cyr" or (long form) "St Cyr L'Ecole".

**Comment by Adrian2k** [comment]
@FrenchGap can comment on this

**Comment by FrenchGap** [comment]
Well given how often this airport is used, that should not be an issue. But if you insist, I approved for it to be modified to "St Cyr". Currently OOF until further notice, unable to create a merge request.
