### ISSUE TITLE
NZCM Oceanic display breaks over the date line

### ISSUE THREAD

**Issue by dsolesvik** [vatsimnetwork/vatspy-data-project#415]
![image](https://user-images.githubusercontent.com/56816890/134717479-2471defe-3677-4c01-bbfc-5e475465bfb4.png)

**Comment by Adrian2k** [comment]
Chocked people actually staff that sector..
It is an easy fix, VATSpy is currently designed to not render lines along the line of -180 and 180, if this sector crosses this line, then it needs to be defined as an additional sector on the other side.

If this is two sectors that split at the 180degree line, then you can resolve it by just slightly adjusting the line from the 180 line.

**Comment by dirtyformal** [comment]
Hey @Adrian2k - I've fixed NZCM, in addition to fixing up our internal NZZC sectors, as well as NTTT and NSFA. 

The only issue is that there isn't an existing GeoJSON file in the master branch - after it was removed not too long ago. I'll just hold off on submitting a PR until 2112 has been merged in, when there's a GeoJSON in the master. 

Cheers 🤙🏼

**Comment by meltinglava** [comment]
@dirtyformal You can base your PR on branch off airac-2112

**Comment by dirtyformal** [comment]
Above PR fixes this issue 🤙🏼

**Comment by dirtyformal** [comment]
Hey @NelisV or @Adrian2k - This Issue can be closed with the merging of the above PR 🤙🏼
