### ISSUE TITLE
FIRBoundaries removed?

### ISSUE THREAD

**Issue by o4oren** [vatsimnetwork/vatspy-data-project#470]
Hi,
I see the FIRBoundaries file was removed from the repo, and I see the discussion on switching to GeoJSON.
Right now there is nothing there though.
Can FIR Boundaries be added back? Or alternatively - can I rely on Boundaries being there as I see on the AIRAC 2112 branch?

**Comment by NelisV** [comment]
We've moved to GeoJSON for maintanence of the datafile, all releases for the forseable future will still include FIRBoundaries.dat generated just before release based on the GeoJSON file.

**Comment by o4oren** [comment]
But the current main branch doesn't have FIRBoundarues.dat.
I pull these once a month to create data for my app (VatView). For now I
added support fir GeoJSON, but its in a dedicated branch fir AIRAC 2112...

**Comment by NelisV** [comment]
For the latest release it's better to use the URL from the VATSIM API. GeoJSON will be added there as well once we release 2112. 

https://api.vatsim.net/api/#tag/map_data
https://api.vatsim.net/api/map_data/

**Comment by o4oren** [comment]
Thanks.
One last question - I see some - very few - FIRs have two sets of polygon
coordinates.
Is this what used to be an extension? And does it now complete a share made
of two halves?

**Comment by NelisV** [comment]
Only when a polygon crosses the anti-meridian this is used. Also described in the GeoJSON spec.
