### ISSUE TITLE
NEA: Updated FIRs and sector splits 

### ISSUE THREAD

**Issue by NEAvACC** [vatsimnetwork/vatspy-data-project#501]
Hi,

I compiled a list of changes for East Africa to include IRL sector splits and to show updated FIRs for Sudan (HSSS) and South Sudan (HJJJ).

_Note: (HJJJ_CTR) only goes up to FL245 anything higher is controller by Khartoum South (HSSS_S) from FL245-999_

[NEA-Updated Sectors.txt](https://github.com/vatsimnetwork/vatspy-data-project/files/8037805/NEA-Updated.Sectors.txt)

Thanks!

**Comment by Adrian2k** [comment]
It does not appear like HAAA would fit under our requirements to add sector splits.
When it comes to Sudan we could add HJJJ, but again for HSSS the sector split goes outside of policy. Be aware that VATSpy does not support level splits.


As stated on the project page: 

Included Sectors
To keep the map clear and not too cluttered, any new additions to the dataset should cover whole FIR's (e.g. HECC/KZFW). Some exceptions can be made for further splits if the (sub)sector is controlled consistently outside of events and the amount of traffic justifies it. This will be reviewed on a case by case basis.

**Comment by NEAvACC** [comment]
Hi, 
That's fine, could you please add HJJJ FIR and make a note it's only up to FL245. 
More details can be found in South Sudan eAIP https://sscaa.co/ 

Thanks

**Comment by NelisV** [comment]
@NEAvACC I don't see you on our list of approved accounts to change data in our repo, can you follow the the process as described in our readme? Also we don't usually implement changes for VACC's, we just check and approve/deny them. Have you tried making an update to the dataset yourself? It's pretty straightforward if you use the right tools.

**Comment by NEAvACC** [comment]
Hi, you should've received an email from VATMENA regarding that, the changes I'm mainly looking to implement is HJJJ FIR which covers GND-FL245 and the East/West sector splits for HAAA FIR.
