### ISSUE TITLE
Update needed for LTAA and its subsectors

### ISSUE THREAD

**Issue by cptalpdeniz** [vatsimnetwork/vatspy-data-project#503]
Hello! LTAA (Ankara Control) is divided into multiple sectors. The correct placements can be found here: 
https://www.trvacc.net/sector/

Thanks!

**Comment by Adrian2k** [comment]
It does not look like these sector splits are staffed consistently outside of events.

As stated on the project page: 

Included Sectors
To keep the map clear and not too cluttered, any new additions to the dataset should cover whole FIR's (e.g. HECC/KZFW). Some exceptions can be made for further splits if the (sub)sector is controlled consistently outside of events and the amount of traffic justifies it. This will be reviewed on a case by case basis.

**Comment by cptalpdeniz** [comment]
It is actually. On top of that, there are multiple FIRs that do not even have ATC at all but are split into their subsectors such as:
- Tehran (Usually no ATC)
- Iraq (No vACC at all)
- Israel (most of them time have ATC but never the subsectors)
- Greece (Greece is always either LGGG_CTR or nothing. The subsectors are almost never used and only used few times during the year in events, yet they have it)
- Italy (again, the subsectors are updated very deeply but ATC does not provide cover most of the time)

Considering most of the countries that have less ATC and CTR activity online have subsectors but Turkey doesn't, I don't see the actual reason why Turkey is not considered for this. If this request was for an other country, it would have been approved. But when it's Turkey, it's not.

**Comment by Adrian2k** [comment]
The policy has only been in effect for a year or so, as the data got more and more cluttered up often for pratically zero use for the users. The area's that already had their splits implemented prior to this are to keep them until they change their sectors again later.

Tehran/Greece - Was included in the dataset long long ago before this was a policy. It has been grandfathered in. If Tehran makes changes in the future they are not to keep these sectors.

Italy/Israel- These are "FIR's" added, not sector splits. For Italy's case, all of the FIR's have different callsigns. For Isreal, seems like an odd way to get sector splits added, most likely would not have been approved with today's policy.

I checked online time on the LTAA sectors from Jan 2021 until today, these are the results:
![image](https://user-images.githubusercontent.com/35482228/153792681-fd41552e-5814-4642-9842-53861473b793.png)

These hours does not justify adding 18 or so different sectors, which in fact would not even light up on VATSpy. I also have an assumtion that 3 of the CTL events has a big factor on these hours aswell.

**Comment by Adrian2k** [comment]
`If this request was for an other country, it would have been approved. But when it's Turkey, it's not.`

This has nothing with countries to do. We have already been rejecting splits in areas such as Spain, USA, Pakistan, Africa.

**Comment by cptalpdeniz** [comment]
![image](https://user-images.githubusercontent.com/17345222/208002558-30933e4b-65b6-4469-b2ef-dd25db88deaf.png)

And how is this satisfied?

**Comment by cptalpdeniz** [comment]
Can we at least implement these sectors which are as you can see have more online hours than most of the sectors in South Korea, Iran and Iraq?

![image](https://user-images.githubusercontent.com/17345222/208003015-d2c4ad62-f286-436c-906a-d63958ba376b.png)

Alp Deniz Senyurt
ACCTR5
