### ISSUE TITLE
Splits in Rhein and Maastricht UIR (EDUU/EDYY)

### ISSUE THREAD

**Issue by jannikvogel** [vatsimnetwork/vatspy-data-project#504]
Hello,

as sector splits in the lower (FIR) sectors are increasingly implemented, I wanted to propose the idea of filling the data project with some splits in the UIRs (as with EURM-E/W).

In the german upper (EDUU/EDYY) we often have the problem, that the whole UIRs (laterally containing different FIRs) are highlighted when staffing one smaller station just covering one part of the UIR (often laterally equal to one of the FIRs). [Funfact: There isn't even a station covering the whole UIR].

Also when EDYY is staffed, even the Upper above EHAA/EBUU/etc. will be highlighted, so stations covering just the german part of EDYY will receive many initial calls from pilots above the benelux states.

As the policy for sector splits in the data project seems to be kind of strict and there will be the approval needed from EDWW, EDGG, EHAA and EBUU, I wanted to ask whether an implementation of upper sectors like mentioned above (I would say circa 7 new splits needed to be implemented) is possible and welcomed?

Regards
Jannik

**Comment by Adrian2k** [comment]
Adding even more sectors to the map in Germany is excessive by this point, it is already starting to become a bit messy.
If you can define the splits using excisting sectors in our dataset, then its fine as entries you add in VATSpy.dat does not clutter the map.

However adding the splits into vatspy.dat does not have any effet on VATSpy, it would only affect other software such as volanta, simaware and other software using our dataset.

**Comment by dsolesvik** [comment]
For EURM-E/-W by the way, the physical callsigns will be changing soon to "EURM-E" and "EURM-W", so that they display correctly on VATSpy.
