### ISSUE TITLE
Berlin Tegel (EDDT) - removal from database?

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#527]
Hi,

maybe the (former) Berlin Tegel airport (ICAO: EDDT) should be removed from the VATSpy database?

It's fully closed (no longer used for any aviation purposes) since 5th May, 2021, and it's also no longer included in the German AIP.

**Comment by Adrian2k** [comment]
@Frenkii @svengcz not sure who here deals with the Bremen area, but do any of you have any comments to removing EDDT?

As long the ICAO is not being reissued to another place, we could keep it in the database for people flying to this "historical" airport.

**Comment by svengcz** [comment]
Yes, we can remove EDDT. We do not serve the airport on VATSIM.
