### ISSUE TITLE
FIR ZBYN boundary is missing

### ISSUE THREAD

**Issue by dneuge** [vatsimnetwork/vatspy-data-project#536]
In the `[FIRs]` section of `VATSpy.dat` ZBYN is defined as:
```
ZBYN|Taiyuan ACC - Beijing|ZBYN|
```

However, the ZBYN FIR boundaries are missing in `Boundaries.geojson` and the `FIRBoundaries.dat` generated from it as of v2204.1.

An airport with the same ICAO code is defined as being handled by FIR ZBPE (not FIR ZBYN?):

```
ZBYN|Taiyuan Wusu|37.748422|112.629125||ZBPE|0
```

**Comment by RudiZhang** [comment]
Hi, ZBYN is not a FIR but ACC in ZBPE FIR. And ZBYN ACC was deleted from 2204. Thanks for let me know, I've removed it from vatspy.dat.
