### ISSUE TITLE
EURM-W & EDYY have overlapping labels

### ISSUE THREAD

**Issue by ChrisXPP** [vatsimnetwork/vatspy-data-project#545]
Hi,

Eurocontrol West (EURM-W) and Maastricht (EDYY) show overlapping labels on the map in those sectors covered by both ATC units.

Screenshot is attached.
![EURM_EDYY_labels](https://user-images.githubusercontent.com/74152765/170835349-3553a6dd-cbc7-4636-b96a-438a72869f30.png)

**Comment by Adrian2k** [comment]
This issue is related to VATSpy itself, not the dataset.
Suggest you report it on the forums.
