### ISSUE TITLE
Permanently closed airfields

### ISSUE THREAD

**Issue by hsugden** [vatsimnetwork/vatspy-data-project#558]
All of these UK airfields can now be removed as they are permanently closed, many now used for other purposes:
- EGXG Church Fenton
- EGXU Linton-On-ouse
- EGSD Great Yarmouth North Denes
- EGYC Coltishall
- EGOD Llanbedr
- EGXD Disforth
- EGDL Lyneham
- EGUF Farnborough Military
- EGDK Kemble Royal AFB
- EGLG Panshangar Holywell Hyde
- EGHB Maypole
- EGUS Lee on Solent Gosport Navy
- EGXJ Cottesmore
- EGWZ Alconbury Royal AFB
- EGUA Upper Heyford Royal AFB
- EGCD Woodford
- EGKD Albourne
- EGLB Brooklands

**Comment by luke11brown** [comment]
Added to the list:

- EGYW Wainfleet
- EGYH Holbeach
- EGXV Leconfield
- EGXN Newton
- EGXH Honington
- EGXF Cowden
- EGVJ Bentwaters
- EGVI Greenham Common
- EGVG Woodbridge
- EGUY Wyton
- EGUP Sculthorpe
- EGUO Colerne
- EGTA Aylesbury Thame

Questions:

- EGYK York Elvington
