### ISSUE TITLE
Display new call sign

### ISSUE THREAD

**Issue by githubvatsim** [vatsimnetwork/vatspy-data-project#576]
CZEG has created a new call sign. It combines the Calgary (CYYC_APP) and Edmonton (CYEG_APP) terminal control areas under one call sign, CZEG_APP (124.450). CYYC_APP and CYEG_APP are unchanged and have been in use for many years. Both existing map rings should display when CZEG_APP is online. Neither will be online with CZEG_APP. The call sign will be live with the AIRAC update for 2208.

Tony Koch
CZEG FE

**Comment by Adrian2k** [comment]
We can only display one approach ring for CZEG_APP.

**Comment by githubvatsim** [comment]
In what format can I provide the data for a ring created for this purpose? We are using AeroNav.

**Comment by Adrian2k** [comment]
The rings can only be around airports.

**Comment by githubvatsim** [comment]
Is the limitation that CZEG_APP is not unique to ONE airport, because a ring created for that call sign would be around airports?

**Comment by Adrian2k** [comment]
You can choose what airport CZEG_APP should be displayed at (assuming there is no airport with the ICAO CZEG), but it can only be displayed at one airport not multiple. This is a software and dataset limitation.

There are plenty of places in the world where an approach covers multiple airports yet only has one approach ring on vatspy, this case is not unique to Calgary and Edmonton.

**Comment by githubvatsim** [comment]
I understand. So, if we choose to associate it with CYYC then the existed ring information could be associated with CZEG_APP? Or could we provide coordinates that would include CYEG? Or vice versa?

**Comment by Adrian2k** [comment]
Either you are overthinking this or I am misunderstanding what you are saying.
The principle is pretty basic, we add CZEG as an "alternative" logon to an airport for example CYYC.

Then there will be an approach ring around CYYC when CYYC_APP or CZEG_APP is online.
We can't associate CZEG to more than one airport. If you want the CZEG approach circle to be centered on CYYC, we can do that.

**Comment by githubvatsim** [comment]
Thanks for your follow up with this. Please associate CZEG_APP with CYYC and we’re done. Tony
