### ISSUE TITLE
Verifying account

### ISSUE THREAD

**Issue by sanek1000804** [vatsimnetwork/vatspy-data-project#590]
Hello! I'm currently working on a big change in one of the zones in Russia, which often uses CTR positions with different prefixes. Now all of them are displayed incorrectly. Please explain how FIR staff needs to verify my account in order for me to submit a pull request. What email should they write to? Or does it happen differently?

**Comment by theShpuntik** [comment]
RTFM!

**Comment by sanek1000804** [comment]
> RTFM!

I have read but still don't understand

**Comment by theShpuntik** [comment]
U are going to make changes for ULLL?

**Comment by sanek1000804** [comment]
Yes

**Comment by theShpuntik** [comment]
U can just ask Kate or Alex to send email with confirmation that u can make changes for ULLL FIR boundaries

**Comment by sanek1000804** [comment]
And how vatspy-data-project staff will check, that this is ULLL staff writing?

**Comment by sanek1000804** [comment]
Ok, thanks
