### ISSUE TITLE
LPPC is duplicated

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#600]
I'm probably not high, but it seems that the LPPC airspace is showing darker than usual.
![image](https://user-images.githubusercontent.com/40349656/196207407-907f3357-311d-4fe7-b642-8580b6c7d340.png)
Upon checking the files, it seems that there is two LPPC entries, one normal and one extension.

**Comment by Adrian2k** [comment]
@NelisV 

LPPC is for some reason defined on line 202, after the LOVV-C definition.
