### ISSUE TITLE
change callsign to BSW_CTR

### ISSUE THREAD

**Issue by tgpetrica** [vatsimnetwork/vatspy-data-project#601]
Hello,
We'd like to update a radar position in VatSpy:
Refference line: [18451 ](https://github.com/vatsimnetwork/vatspy-data-project/blob/24ff147886fadbd5a97dd46e00734ab8eb63d751/VATSpy.dat#L18451)
Call sign: BSW_CTR
Call sign name: Black Sea West Control
Type: top-down
Covering LRBB, LUUU and LBSR FIRs when local ATC is offline

**Comment by dsolesvik** [comment]
I'm happy to do this, give me a weekend.

**Comment by tgpetrica** [comment]
Thank you!
