### ISSUE TITLE
Missing boundaries

### ISSUE THREAD

**Issue by Soofushka** [vatsimnetwork/vatspy-data-project#639]
Hello.There is missing sector somewhere in Pacific Ocean
![image](https://user-images.githubusercontent.com/108477923/210536573-942c6163-182d-46d8-a5f3-773a9e0e1dd9.png)

**Comment by dsolesvik** [comment]
This FIR doesn’t exist IRL and is labelled “XX02” - no FIR. Put simply, nobody flies there and nobody controls it

**Comment by Soofushka** [comment]
Ok, thanks)
