### ISSUE TITLE
Manchester TMA Airpsace Not Added

### ISSUE THREAD

**Issue by luke11brown** [vatsimnetwork/vatspy-data-project#65]
Ref #50 

The only part which was included was the removals from VATSpy.dat
Nil additions were merged in commit 08dab753a8c4da4a57216af7357e4871250f14d6

**Comment by faulder** [comment]
Came here to post it was looking very lonely without MAN_CTR, this'll be why.

**Comment by nepetadosmil** [comment]
Fixed in #66. Apologies 😬
