### ISSUE TITLE
BGSF is now covered top-down by Reykjavik Control (BIRD_x_CTR)

### ISSUE THREAD

**Issue by mythicfci** [vatsimnetwork/vatspy-data-project#664]
I'm a controller in the Reykjavik CTA of VATSIM Scandinavia. We recently changed the SOP for Reykjavik Control so that any West positions (BIRD_Wx_CTR, where x is a number from 1-3) or South positions (BIRD_Sx_CTR, x=1-3) cover BGSF top-down when there is no local BGSF ATC online.

See here for the SOP: https://vatsim-scandinavia.org/applications/core/interface/file/attachment.php?id=4169&key=db388f1c7972e2c1d5ef09c5a8a6bbde

Could VATSpy be updated to appropriately list BIRD W or S positions as ATC for BGSF when online?

**Comment by Adrian2k** [comment]
Not really, the FIR associated is supposed to be the main FIR which in this case is BGGL.
Using the airport details page in VATSpy is neither a good way of seeing top-down ATC.

**Some examples of this are:**
Norway - ENSV, ENOS, ENBD is the "main" defined FIR's, so ENOR_CTR can not be included.
Sweden - You have ESOS which covers the whole FIR, but ESMM that only covers parts of the FIR. Airports can only display one.
Ireland (EIDW) - There are two FIR's defined in this area, EISN and EIDW - only one can be used, in this case EISN is used.
France (LFSB) - This airport is covered by Swiss if there is no other ATC provided there.


You will be better with either including this information in the controller info, or giving a heads up to plits connecting there. Doubt that people even use VATSpy airport details to see the ATC list.
