### ISSUE TITLE
excessive latitude for YBBN

### ISSUE THREAD

**Issue by dneuge** [vatsimnetwork/vatspy-data-project#674]
The third entry for YBBN in VATSpy.dat, section Airports, defines an excessive latitude in the just released v2304.1 tag:

```
YBBN|Brisbane|-27.384167|153.1175|BN|YINL|0
YBBN|Brisbane|-27.384167|153.1175|BN-S|YINL|0
YBBN|Brisbane|327.384167|153.1175|BN-F|YINL|0
```

This appears to be a typo, the leading `3` should probably be a `-`.

**Comment by chrisg06** [comment]
fixed in #675
