### ISSUE TITLE
Japan airspace have been changed

### ISSUE THREAD

**Issue by mika0802** [vatsimnetwork/vatspy-data-project#682]
HII This is mika form VATJPN
We have changed our sectorline last year
Can we request update to fix the line in vatspy?

https://vatjpn.org/forum/5/3313

SECTORLINE:RJBG_CTR
COORD:N033.22.02.682:E128.10.02.063
COORD:N033.08.00.000:E128.59.08.000
COORD:N033.06.15.000:E128.50.06.000
COORD:N032.49.01.000:E128.35.26.000
COORD:N032.47.44.988:E128.34.27.119
COORD:N032.45.22.824:E128.33.08.280
COORD:N032.42.51.263:E128.32.20.040
COORD:N032.40.14.988:E128.32.03.840
COORD:N032.37.38.712:E128.32.20.040
COORD:N032.35.07.187:E128.33.08.280
COORD:N032.32.44.988:E128.34.27.119
COORD:N032.30.36.467:E128.36.14.040
COORD:N032.28.45.552:E128.38.25.800
COORD:N032.27.15.552:E128.40.58.439
COORD:N032.26.09.275:E128.43.47.280
COORD:N032.25.28.668:E128.46.47.279
COORD:N032.25.12.000:E128.49.28.000
COORD:N032.25.13.000:E128.59.52.000
COORD:N031.30.56.000:E128.59.52.000
COORD:N031.00.51.000:E128.59.52.000
COORD:N030.00.13.000:E128.59.52.000
COORD:N029.37.13.000:E128.26.01.000
COORD:N027.43.51.000:E125.45.34.000
COORD:N026.29.17.000:E127.47.22.000
COORD:N026.27.31.000:E129.43.25.000
COORD:N027.52.14.000:E130.30.52.000
COORD:N029.27.39.000:E131.39.23.000
COORD:N030.00.13.000:E131.29.59.000
COORD:N030.00.13.000:E131.29.52.000
COORD:N030.00.13.000:E131.29.52.000
COORD:N030.39.52.000:E132.08.47.000
COORD:N030.47.59.000:E132.19.26.000
COORD:N030.51.09.000:E132.23.45.000
COORD:N032.00.13.000:E133.59.51.000
COORD:N032.07.13.000:E134.25.10.000
COORD:N032.35.47.000:E134.59.54.000
COORD:N033.35.03.999:E134.59.50.000
COORD:N033.57.03.000:E134.56.55.999
COORD:N034.18.26.000:E134.54.05.000
COORD:N034.30.26.000:E135.06.08.999
COORD:N034.17.01.000:E133.57.30.000
COORD:N034.14.40.000:E133.51.48.000
COORD:N034.12.00.000:E133.30.34.000
COORD:N034.19.56.000:E133.28.56.000
COORD:N034.45.57.000:E133.10.30.000
COORD:N035.24.48.000:E132.42.31.000
COORD:N035.06.53.367:E129.46.22.789
COORD:N034.39.59.999:E129.09.59.999

SECTORLINE:RJDG_CTR
COORD:N031.22.59.000:E134.59.50.000
COORD:N030.06.03.000:E133.06.36.000
COORD:N029.31.40.000:E132.17.38.000
COORD:N028.49.53.000:E133.25.49.000
COORD:N028.07.53.000:E132.45.35.000
COORD:N027.23.21.000:E132.04.29.000
COORD:N026.45.23.000:E131.57.04.000
COORD:N026.37.58.000:E131.51.18.000
COORD:N026.24.14.000:E131.38.35.000
COORD:N025.52.28.000:E131.09.25.000
COORD:N025.05.36.000:E130.34.45.000
COORD:N024.51.36.000:E130.22.03.000
COORD:N024.35.05.000:E129.44.18.000
COORD:N023.14.47.000:E128.42.45.000
COORD:N021.00.00.000:E126.50.47.107
COORD:N021.00.00.000:E121.30.00.000
COORD:N023.30.00.000:E124.00.00.000
COORD:N030.00.00.000:E124.00.00.000
COORD:N030.00.00.000:E125.25.00.000
COORD:N032.30.00.000:E126.50.00.000
COORD:N032.30.00.000:E127.30.00.000
COORD:N033.22.02.682:E128.10.02.063
COORD:N034.40.00.000:E129.10.00.000
COORD:N035.06.53.368:E129.46.22.790
COORD:N035.33.28.292:E130.22.20.631
COORD:N035.31.26.000:E132.05.30.000
COORD:N035.30.28.000:E132.38.24.000
COORD:N035.24.48.000:E132.42.30.999
COORD:N034.19.55.999:E133.28.55.999
COORD:N034.12.00.000:E133.30.34.000
COORD:N034.14.40.000:E133.51.48.000
COORD:N034.17.01.000:E133.57.30.000
COORD:N034.30.26.000:E135.06.08.999
COORD:N034.18.26.000:E134.54.05.000
COORD:N033.57.03.000:E134.56.55.998
COORD:N033.35.03.998:E134.59.50.000

**Comment by NelisV** [comment]
Hey Mika, 

Could you please follow the admission procedure for new submitters as per the readme?
We need approval from your (sub)division staff. 

Niels.

**Comment by Adrian2k** [comment]
Feel free to submit a PR and get an staff member to approve the changes - but we are not submitting data on behalf of other FIR's.
