### ISSUE TITLE
St Athans EGSY

### ISSUE THREAD

**Issue by louielister** [vatsimnetwork/vatspy-data-project#69]
(Sorry if this is the wrong place)

Sheffield City Airport [EGSY] was closed in 2008. Since then, St Athans has had a recent ICAO change from EGDX to EGSY. 

VAT-Spy shows both old ICAOs. EGSY needs removing from its old location [https://prnt.sc/sja41a] and EGDX needs renaming to EGSY.

Louie

**Comment by faulder** [comment]
Are your data files up to date?

EGSY only appears once, https://github.com/vatsimnetwork/vatspy-data-project/blob/master/VATSpy.dat#L2004

**Comment by louielister** [comment]
I was under the impression I already had the latest one. However, I'm not sure where I can find the latest downloads. If you could drop me a link on Slack, that'd be most appreciated! 

Closed as issue already fixed.
