### ISSUE TITLE
Updated ICAO code: MHSC -> MHPR

### ISSUE THREAD

**Issue by DAL2503** [vatsimnetwork/vatspy-data-project#690]
Needing the Nueva Ocotepeque (MHSC) ICAO code changed to Comayagua/Palmerola International (MHPR).

**Comment by ChrisXPP** [comment]
A bit misleading... 
Nueva Ocotopeque is already with its correct code (MHNV).
It seems Comayagua/Palmerola Intl (MHPR) is missing...

**Comment by DAL2503** [comment]
> A bit misleading... Nueva Ocotopeque is already included with its correct code (MHNV). It seems Comayagua/Palmerola Intl (MHPR) is missing...

My mistake, I was going off of what Vatspy called MHSC when entered in. 
The Soto Cano Airport (MHSC) is now the new Comayagua/Palmerola Intl (MHPR).

**Comment by ChrisXPP** [comment]
@DAL2503 I created a PR regarding this issue. The new airport will be named "Palmerola" (w/o "Intl") to keep this in sync with the other entries for Honduras.

**Comment by DAL2503** [comment]
> @DAL2503 I created a PR regarding this issue. The new airport will be named "Palmerola" (w/o "Intl") to keep this in sync with the other entries for Honduras.

Awesome! Much appreciated!

**Comment by ChrisXPP** [comment]
Issue resolved with latest AIRAC 2208 release. Can be closed.
