### ISSUE TITLE
Remove RKRR_A from UIR

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#719]
The new VATspy update is showing RKRR_A as a UIR.

To remove RKRR_A from UIR, and for VATKOR's consideration if they would like to create a FIR for RKRR_A to show the coverage difference between RKRR_CTR & RKRR_A_CTR

![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/40349656/0f3e3844-0cc6-4075-b10c-060116d44080)

**Comment by amosngSP** [comment]
@lancard maybe you'd like to take a look at this

**Comment by lancard** [comment]
I understood. proceed your request. :)

**Comment by lancard** [comment]
Do you want me to work on it?

**Comment by lancard** [comment]
now working on it: https://github.com/vatsimnetwork/vatspy-data-project/compare/master...lancard:vatspy-data-project:patch-1
