### ISSUE TITLE
Addition of Sub-Sectors?

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#725]
The new vat-spy update now only shows sub-sectors, if they come online. Otherwise, only the primary FIR will be shown.

I understand that the policy is currently to only include sub-sectors if they are consistently controlled outside of events, probably to reduce clutter on the vatspy map, but with this new change, are we expecting the policy to change as well? Or it will still remain the same?

**Comment by Adrian2k** [comment]
The policy will change, but until it does please only submit sectors that is beneficial/useful to include.
Adding every possible sector is not the way to do things, at least for now.

**Comment by Adrian2k** [comment]
Policy has been changed
