### ISSUE TITLE
wrong FIR (BSW, instead of LUUU) assigned to traffic

### ISSUE THREAD

**Issue by tgpetrica** [vatsimnetwork/vatspy-data-project#738]
Hello,

The plane is in LUUU FIR (Chisinau FIR), but it shows Black Sea West Radar FIR. How can we change that?
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/57829402/0dcc7788-e34a-4076-b004-84b6fb7e885d)

**Comment by dsolesvik** [comment]
To Adrian and Niels, would having BSW_CTR as a subsector fix this issue, under the new rules/VATSpy update? Would that even be possible?

**Comment by Adrian2k** [comment]
> To Adrian and Niels, would having BSW_CTR as a subsector fix this issue, under the new rules/VATSpy update? Would that even be possible?

Depends on what type sector it is..
Is it an upper-sector only or does it work like ADR_CTR where its multiple FIRs top-down.

**Comment by tgpetrica** [comment]
> > To Adrian and Niels, would having BSW_CTR as a subsector fix this issue, under the new rules/VATSpy update? Would that even be possible?
> 
> Depends on what type sector it is..
> Is it an upper-sector only or does it work like ADR_CTR where its multiple FIRs top-down.

Hello, 
BSW_CTR was a top down sector, but at the moment, for the past 3 years , we were not able to open it due some issues on how the callsign and vACC Divisions at the moment it had been closed. 

LUUU and LRBB are both under the same vACC (under EUD) - top down sectors as FIRs.

**Comment by tgpetrica** [comment]
Hello @Adrian2k ,

Since BSW_CTR is no more in use, could we delete it from the database and make sure the LRBB and LUUU FIRs are covered top down as individual FIRs?

**Comment by Adrian2k** [comment]
> I'll create a PR next week with this LRUB, BSW and LRBB/LUUU FIRs to resolve this issue.

Was this resolved?

**Comment by tgpetrica** [comment]
Hello, not yet, but we can close it for now and maybe reopen later.
