### ISSUE TITLE
Missing sectors

### ISSUE THREAD

**Issue by ephendi** [vatsimnetwork/vatspy-data-project#745]
There are missing new sectors from airac update 10

See
https://euc-vacc.net/sectors

**Comment by Adrian2k** [comment]
Please be more specific - we have all of these as far as I can see:

https://github.com/vatsimnetwork/vatspy-data-project/blob/403f1f38fc974a606d792b47b79c35e4a9494411/VATSpy.dat#L18568-L18576

**Comment by ephendi** [comment]
When i report to vattastic.com about missing sector in map they send me answer all data are from vatspy project so i send you info. Peter Od: Larry Wimble ***@***.***>Dátum: 10. novembra 2023, 17:09:38 SEČPre: Peter Zimen ***@***.***>Predmet: Re: Feature not working or rendering properly﻿I'm not sure what you mean.I get nearly all of the my map data from the VatSpy Data Project on github.  If it's not in their database, chances are it's not going to show up on the Vattastic map.LarryOn 11/9/2023 1:57 AM, Vattastic Website wrote:Feedback received from Vattastic site:Realname    : Peter ZimenCid         : 1164635Email       : ***@***.***     : Feature not working or rendering properlyConfirm     : onComment     : Hello,new eurocontrol facilities are still not visible on map :(https://euc-vacc.net/sectorsPeterDňa 10. 11. 2023 o 17:55 užívateľ Adrian Bjerke ***@***.***> napísal:﻿
Please be more specific - we have all of these as far as I can see:
https://github.com/vatsimnetwork/vatspy-data-project/blob/403f1f38fc974a606d792b47b79c35e4a9494411/VATSpy.dat#L18568-L18576

**Comment by ephendi** [comment]
I report missing sector on vattastic.com and they inform me all data have from vatspy so ball is on his site.

**Comment by Adrian2k** [comment]
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/38fcf3b5-8639-499c-a9f7-38361d73f3a6)

Vattastic uses old data, they will need to update their dataset. Currently release is AIRAC 2311, their database is 2 releases behind the current release.
