### ISSUE TITLE
RU-NWC covers Murmansk Oceanic

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#75]
RU-NWC should include ULMM (Murmansk) Oceanic as they cover this area according to controller info.

**Comment by Connorseds2002** [comment]
Hi there just want to confirm with this is thas an fss or a ctr @Adrian2k

**Comment by kusterjs** [comment]
This seems to be implemented in the current version

**Comment by Adrian2k** [comment]
> This seems to be implemented in the current version

Have you seen ULMM Oceanic been light up with RU-NWC has been online? As far as I know, there has not been any attempt at fixing this issue yet, and when I opened this issue only ULMM Domestic lights up, not the oceanic sector.

**Comment by kusterjs** [comment]
Ah, ok. I think this won't be possible as both sectors use the same designator, hence the first defined will be taken.

**Comment by amosngSP** [comment]
Was thinking about this, since they do cover top-down for all airfields, it might be easier to just draw it like how Adria Radar did it.

**Comment by Adrian2k** [comment]
Closed the issue as its not possible to resolve it in the data files.
