### ISSUE TITLE
EUC-EN_CTR wrong map

### ISSUE THREAD

**Issue by ephendi** [vatsimnetwork/vatspy-data-project#751]
Hello,
EUC-EN_CTR facility is not coverage Austrian airspace. 

Only: EPWW, LKAA, LZBB, LHCC

**Comment by jannikvogel** [comment]
LOVV is covered by EUC-ME, not -EN. At least that is what EUC told the OPS teams and what has been setup in GNG.

**Comment by ephendi** [comment]
Yes but on vattastic map is online when i’m on EUC-EN. They download data from VatSpy airac 23.11..

Peter

**Comment by ephendi** [comment]
I wrote you because i see on map online EUC-EN over austria. This is wrong, as you confirm. Somewhere is problem. On Airac from Vatspy or on vattastic, they have data from vatspy…

**Comment by ClipperWings** [comment]
@ephendi 
Fix to be applied soon
