### ISSUE TITLE
New install cannot add favorites

### ISSUE THREAD

**Issue by triplesevenbob** [vatsimnetwork/vatspy-data-project#76]
Cannot create a new favorites with pilots in a list of their CIDs only can select airports and atc stations as favorites

**Comment by triplesevenbob** [comment]
My favorites was corrupted in one of the updates and I cannot add new favorites only set atc stations and airports as favorites.

**Comment by nepetadosmil** [comment]
This doesn't modify any of the favorites files, nor does it modify any program. I highly doubt this is the cause of your issue, since nobody amongst all the other people which use these files have reported it either. Please try reinstalling VATSpy and ask in the VATSIM Forums if it doesn't work.

**Comment by triplesevenbob** [comment]
> This doesn't modify any of the favorites files, nor does it modify any program. I highly doubt this is the cause of your issue, since nobody amongst all the other people which use these files have reported it either. Please try reinstalling VATSpy and ask in the VATSIM Forums if it doesn't work.

It must have changed the handling of favorites as my xml config caused vatspy to not be loading and I needed a clean install. Now on a clean install I cannot create any favorites of pilots.

**Comment by nepetadosmil** [comment]
As stated in my initial comment, this data update does not modify any of the configuration files or modify the program itself. It is just a mere coincidence that it happened after updating the datafiles, but it is not the cause of it.
