### ISSUE TITLE
HKNA Changes

### ISSUE THREAD

**Issue by notbxno** [vatsimnetwork/vatspy-data-project#765]
As of 12/12/2023, we have added in a new "South" sector for the HKNA airspace, on frequency 125.300, known as "Nairobi South"

HKNA_CTR will cover S when S is offline.

![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/116590361/9a7851fd-1025-4629-be4b-9934d4c7877b)

**Comment by Adrian2k** [comment]
Feel free to submit a PR and get an staff member to approve the changes - but we are not submitting data on behalf of other FIR's.

**Comment by notbxno** [comment]
By staff member, do you mean a staff member of the division? Because if so, I am one.
