### ISSUE TITLE
GMMM CTR Changes

### ISSUE THREAD

**Issue by LocatedAir** [vatsimnetwork/vatspy-data-project#767]
Hi,

I noticed on Vatspy, that when we connect as GMAC_CTR it works fine but GMMM_CTR should no longer be including GMAC_CTR. We changed this a while back. Now GMMM_CTR only covers the land, while GMMM_ALL_CTR covers both GMAC and GMMM.

Can a fix be made for this?

**Comment by Adrian2k** [comment]
Feel free to submit a PR and get an staff member to approve the changes - but we are not submitting data on behalf of other FIR's.
