### ISSUE TITLE
Wrong sector displayed for EDWW_B_CTR

### ISSUE THREAD

**Issue by Balu1412** [vatsimnetwork/vatspy-data-project#769]
Hello,
In Germany (FIR EDWW) the EDWW_B_CTR gets displayed with the boarders of EDMM_G_CTR wich is incorrect, EDWW_B_CTR should have the same sector displayed as EDWW_M_CTR. 
This problem leads to confusion for pilots because it displays EDWW_B_CTR controlling EDDP, EDDC and EDDE, but it does not cover any of these, it should cover EDDB, EDAH and ETNL, like EDWW_M_CTR does.

Thank you for your help and this nice project!

**Comment by Adrian2k** [comment]
Should be resolved with latest release
