### ISSUE TITLE
Missing airport EDPR

### ISSUE THREAD

**Issue by Balu1412** [vatsimnetwork/vatspy-data-project#770]
Hello,
recently I noticed that the Airbus Helicopter airfield (EDPR) in Donauwörth (Germany) is missing in your database. The field is an uncontrolled heliport with a flight information station, an ATIS, a radio mandatory zone (RMZ) with IFR departure and arrival procedures. It would be nice to see this field when ATC is online :)
I already prepared the needed line for your database:

EDPR|Donauwörth Heliport|48.7075|10.76944||EDMM|0

with kind regards

**Comment by ziplock1** [comment]
https://github.com/vatsimnetwork/vatspy-data-project/pull/772

**Comment by ziplock1** [comment]
@Balu1412 Fixed in merged https://github.com/vatsimnetwork/vatspy-data-project/pull/772 .
