### ISSUE TITLE
Nakhichevan' (UBBA_S_CTR) does not exist on VATSPY

### ISSUE THREAD

**Issue by SebaDavinch** [vatsimnetwork/vatspy-data-project#780]
Hello!
I've mentioned that South sector of Baku (UBBA_S_CTR) doesn't exist on VATSPY.

In real life Baku does have own sector in Nakhichevan with separate freq 120.800
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/68696477/46812532-dc86-4d27-b190-cd6cd0cc48e8)

Also Nakhichevan is under united Baku sector (125.500) 
And could be under Caucasus Radar (RU-SC_FSS) (because Caucasus Radar includes UBBA FIR)

But when RU-SC_FSS or UBBA_CTR are online - there's no Nakhichevan
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/68696477/0d177c38-c74b-4380-9477-7dd793356a90)
![VATSpy_UjYtBuK0sN](https://github.com/vatsimnetwork/vatspy-data-project/assets/68696477/83e20d09-cf8a-4637-b963-9c2280648f73)

If it will be possible to add UBBA_S to UBBA_CTR and RU-SC_FSS (at least) - will be great!

Thanks

**Comment by Adrian2k** [comment]
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/dff5ea78-8af8-44d2-ace8-714098a82483)

It does excist, but there is no good way of displaying 2 seperate polygons online at once.
It can easily be added to be displayed when RU-SC_FSS is online though.

**Comment by Adrian2k** [comment]
> If it possible to add under RU-SC_FSS coverage - will be great.

Resolved in [3f02f42](https://github.com/vatsimnetwork/vatspy-data-project/pull/797/commits/3f02f426430b8050e1489d3553118d1e74e0949a)
