### ISSUE TITLE
YAMB TWR showing in Madagascar, YAMB ATIS showing in the correct location

### ISSUE THREAD

**Issue by miguelalbano** [vatsimnetwork/vatspy-data-project#783]
Verified YAMB coordinates on the .dat file and they seem good. Not sure if this a data issue or a vatSpy issue.

![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/30835922/4685d26b-4a49-4030-8530-bc101e0cadf6)

**Comment by Adrian2k** [comment]
Is the logon actually YAMB_TWR or something else?

**Comment by chrisg06** [comment]
Logon is AM_TWR

**Comment by Adrian2k** [comment]
It is because it is not properly defined - fixed in [dc6b4f4](https://github.com/vatsimnetwork/vatspy-data-project/pull/796/commits/dc6b4f4ad036b51d681e1ae90699144d6b5540a7)
