### ISSUE TITLE
MHCC_CTR not showing on map

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#80]
I have tried investigating this but without finding an answer for it.
MHCC is not showing on VATSpy, but seems to cover either the whole MHTG or somewhere in MHTG's FIR, however on skyvector MHTG FIR does not excist, it only shows MHCC in that area. 

Looking on vatsim stats, both MHTG_CTR and MHCC_CTR seems to be actively in use. 

Controller info of MHCC_CTR were: "Cenamer Control | English & Spanish^Â§vatca.net" and had ATIS setup at MHTG airport.

**Comment by nepetadosmil** [comment]
Had a chat with their regional director. Apparently MHTG_CTR doesn't exist anymore and was replaced by MHCC_CTR :)
