### ISSUE TITLE
NZAA_CTR not showing on map

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#81]
Belongs somewhere in New Zealand, I suspect it cover the whole country but unable to find the documentation on it.
According to their sectorfile it covers NZCR and NZCB as "Auckland Oceanic Radar"
Sectorfiles: https://www.vatnz.net/airspace/sector_files/

Controllerinfo: Auckland Control^Â§Charts- www.vatnz.net/airspace/airports/

**Comment by nepetadosmil** [comment]
@FlynZSky Can you pass this on to your people, plz?
