### ISSUE TITLE
LGMD is gone after 2404

### ISSUE THREAD

**Issue by daniluk4000** [vatsimnetwork/vatspy-data-project#818]
I don't know if this is intended but LGMD feature is gone after 2404 AIRAC update. LGMD doesn't have it's own feature anymore and basically exists for nothing (this broke my parsing for example, I'll fix this for my service but I don't know how other services will react on that)

![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/10450717/844586ea-9427-481b-8602-ccccc5495701)

![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/10450717/3616127e-729c-43c2-b573-b5e36604f328)

If this is a mistake then LGMD feature should come back, and if not - be removed from .dat file

**Comment by ziplock1** [comment]
@nakoale

**Comment by SpyrosTTK** [comment]
Hello! We are examining the situation. We will probably be updating the data files again, due to a mistake during the push. They should be good by night today. Speaking on @nakoale ‘s behalf.
