### ISSUE TITLE
BAE Warton aerodrome name typo

### ISSUE THREAD

**Issue by kristiankunc** [vatsimnetwork/vatspy-data-project#826]
The airport is currently named "BAe Warton" while the company name is BAE systems (https://en.wikipedia.org/wiki/BAE_Systems) https://github.com/vatsimnetwork/vatspy-data-project/blob/2c0eebc1bf47d04c02bc113edd9898901070e6ba/VATSpy.dat#L1927

**Comment by williammck** [comment]
BAE Systems used to be British Aerospace (BAe) which is where that name originates.

I'm seeing most places just refer to it as Warton Aerodrome now. Official address according to NATS still refers to it as BAe Systems, Warton Aerodrome.

**Comment by kristiankunc** [comment]
I was unaware of that, thought the comapny name change reflected the aerodrome name as well.
