### ISSUE TITLE
KZOA text

### ISSUE THREAD

**Issue by CaptainRicsike** [vatsimnetwork/vatspy-data-project#835]
Good day!
Loving the work! Any chance the KZOA text could be moved to some other area of the sector as it can be very busy and unreadable if many people are flying around the San Fran area :) 
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/124945457/11fd3eda-af8c-44a9-a774-afad9211e809)
Thanks in advance!!
Richard M

**Comment by williammck** [comment]
We don't control how text is displayed on the screen, this project is only for the boundaries.
