### ISSUE TITLE
ENBD/ULLL/Unallocated airspace lines wrong

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#858]
According to AIP Norway:
![image](https://github.com/user-attachments/assets/48c5f87e-07e1-4330-bc2d-a8e99ce24fc5)

According to Skyvector:
![image](https://github.com/user-attachments/assets/9a36c27f-2827-4495-884d-bb4339b21658)

According to Navigraph:
![image](https://github.com/user-attachments/assets/9ba0cdc5-2b9a-4d86-8340-a84bd6bdd800)

However VATSpy dataset shows following:
![image](https://github.com/user-attachments/assets/c75c63d8-8747-4177-a859-2b933237974d)

ULLL FIR should go more like this:
![image](https://github.com/user-attachments/assets/e829d497-182a-4e70-92fe-5077ab339b2c)

**Comment by Adrian2k** [comment]
From Norwegian sectorfile:
![image](https://github.com/user-attachments/assets/431dda17-e1b2-41cd-a99d-e53016dd69c0)

The coordinates we have in our sectorfile is:
ENBD
```
N071.30.00.000	E032.05.00.000
N070.10.00.000	E032.05.00.000
N070.00.00.000	E031.08.00.000
N069.47.41.000	E030.49.04.000
```

ULLL
```
N071.00.00.000	E030.00.00.000
N070.22.00.000	E031.43.00.000
N070.00.00.000	E031.08.00.000
N069.47.41.000	E030.49.04.000
```
![image](https://github.com/user-attachments/assets/469836f2-0321-4d89-b841-414c38556803)

**Comment by Adrian2k** [comment]
@daniluk4000 as you have previously worked on these sectors - something you want to look into and fix?

**Comment by daniluk4000** [comment]
> @daniluk4000 as you have previously worked on these sectors - something you want to look into and fix?

Hey! We will take a look with the guy who made us new sectors
