### ISSUE TITLE
FIR OBBB-E defines "oceanic" field as 9 (typo?)

### ISSUE THREAD

**Issue by dneuge** [vatsimnetwork/vatspy-data-project#895]
`OBBB-E` currently holds a value of `9` in the `oceanic` field: (comments added by me)

```jsonc
{
  "type": "Feature",
  "properties": {
    "id": "OBBB-E",
    "oceanic": "9", // should probably be only 0 or 1?
    "label_lon": "52.491067",
    "label_lat": "26.202716",
    "region": "EMEA",
    "division": "VATMENA"
  },
  "geometry": {
    "type": "MultiPolygon",
    "coordinates": [
      [
        // omitted from this excerpt
      ]
    ]
  }
}
```

While I don't know what the exact format should look like I suspect this is a typo and maybe was probably supposed to be `0` unless there has been some recent change. I've never encountered values other than `0` and `1` on that field before and `OBBB-E` is also the only FIR using that value in the current revision.

**Comment by amosngSP** [comment]
Looks like an error. I'll do a PR to amend it.
@DedpewlControl fyi

**Comment by DedpewlControl** [comment]
Hello! This is indeed an error on my end. This sector is not an oceanic sector.

**Comment by dneuge** [comment]
Thanks a lot! :)
