### ISSUE TITLE
WBGG_CTR Missing

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/vatspy-data-project#96]
![image](https://user-images.githubusercontent.com/35482228/93355028-e9f40b80-f83d-11ea-8316-44995c5d90c8.png)

Controller info: `Callsign "KUCHING RADAR"^Â§Top-Down radar for airports WBGG WBGS WBGB^Â§Service for BOTH Departures and Arrivals`

It should be there somewhere. I found this picture on the VATSIM Discord:
![image](https://user-images.githubusercontent.com/35482228/93355138-06904380-f83e-11ea-8dfa-fefe5c1dc119.png)

**Comment by amosngSP** [comment]
Coordinates:
`WBGG|0|0|34|0.833333|108.400000|8.316667|120.000000|2.543970|110.651110
1.000000|108.975000
1.133333|108.950000
1.333919|109.048794
1.517272|109.065464
1.650617|109.298825
1.933978|109.348831
1.983983|109.582192
2.067325|109.632197
2.000653|109.615531
1.933978|109.532186
1.800633|109.565525
1.783964|109.665536
1.617281|109.648867
1.417261|109.832222
1.417261|109.915567
1.283914|109.982242
1.200572|110.065583
1.183906|110.165597
1.000000|110.266667
0.833333|110.550000
0.900667|110.816558
1.000553|110.915686
1.067228|111.249061
0.933881|111.532428
1.017222|111.632442
0.967217|111.849133
1.117231|111.949144
1.133900|112.149169
1.433931|112.249181
4.040450|112.509580
4.040450|110.834760
2.250000|108.500000
1.000000|108.500000
1.000000|108.540000`

**Comment by amosngSP** [comment]
Refer to pull request #161
